### ISSUE TITLE
missing_docs not working in Swift 3 code

### ISSUE THREAD

**Issue by Tableau-David-Potter** [realm/SwiftLint#852] opened 2016-10-22 00:51 UTC
I've just converted one of my repos to Swift 3 and now I'm getting a ton of missing_docs warnings.  The items in question did not fail before the conversion and are all properly documented.

Any ideas?

Thanks,
***David***

**Comment by norio-nomura** [comment] 2016-10-22 02:50
This is a duplicate of #728.

**Closed by norio-nomura** 2016-10-22 02:50 UTC
