### ISSUE TITLE
Adding SwiftLint Using SPM Includes Extra Packages

### ISSUE THREAD

**Issue by faizan-ali-mlk** [realm/SwiftLint#5434] opened 2024-01-21 13:44 UTC
Hi,

I am trying to add SwiftLint using Swift Package Manager (SPM), but I don't know why it contains extra packages with it. I tested with CocoaPods, but there it is not adding any extra packages. I also tried to install other packages using SPM, like Alamofire, but that also did not add extra packages with it. I searched the issue logs, but I don't think anyone else is experiencing this issue. Please see the screenshots for the issue display.

Swiftlint using package manager

<img width="263" alt="Screenshot 2024-01-21 at 14 41 47" src="https://github.com/realm/SwiftLint/assets/6730214/29e5a60c-b134-4202-ad52-ebd32cfeb684">
<img width="862" alt="Screenshot 2024-01-21 at 14 42 00" src="https://github.com/realm/SwiftLint/assets/6730214/0f73ab09-f564-431f-a44c-1cc4e25786b7">

AlamoreFire Using Package manager

<img width="268" alt="Screenshot 2024-01-21 at 14 42 17" src="https://github.com/realm/SwiftLint/assets/6730214/6fa20192-3fa8-4e30-aa2a-99d0a0424c9d">
<img width="862" alt="Screenshot 2024-01-21 at 14 42 21" src="https://github.com/realm/SwiftLint/assets/6730214/f70127b4-557f-401e-a0ab-b306becd772b">

**Comment by SimplyDanny** [comment] 2024-01-21 16:49
Actually, it shouldn't be surprising that Swift packages depend on other packages transitively. However, on macOS, the SwiftLint plugin depends in a compiled binary only. So the sources shouldn't be required. There seems to be a bug in Xcode/Swift Package Manager, though, so that still all dependencies are loaded and compiled.

#5404 appears to fix this. Please have a try with the current `main` branch and let us know if it works.

**Comment by preciouslogic** [comment] 2024-01-21 17:22
Thank you for the quick reply. I tested it by setting the main branch in SPM, but the result is the same.

<img width="921" alt="Screenshot 2024-01-21 at 18 16 41" src="https://github.com/realm/SwiftLint/assets/6730214/4ed5556e-7597-47b3-9024-28fdb69dce34">
<img width="396" alt="Screenshot 2024-01-21 at 18 17 54" src="https://github.com/realm/SwiftLint/assets/6730214/d6c1a1aa-0a3b-45d0-b82c-6eb39431e25e">


I am also confused about one more flow. When I add the package, I get this popup.


<img width="1088" alt="Screenshot 2024-01-21 at 18 15 28" src="https://github.com/realm/SwiftLint/assets/6730214/5c395282-a384-44bc-9b83-44c3aa4cbe7f">


If I set the target for my app, I encounter the following errors, and my project does not compile. However, it works without selecting the target. I am sharing this information in case you can help me understand why that popup is appearing.


<img width="399" alt="Screenshot 2024-01-21 at 18 16 32" src="https://github.com/realm/SwiftLint/assets/6730214/8c719a59-a056-41d6-b35e-67836a214ca6">

**Comment by SimplyDanny** [comment] 2024-01-23 19:21
> If I set the target for my app, I encounter the following errors, and my project does not compile.

SwiftLint can also be consumed as a library (e.g. to develop your own version with extensions). It's a normal Swift package that provides three products: the executable, the library and the plugin.

To use the plugin only you must not assign the other products to any of your targets. Otherwise, they will be seen as dependencies that must be compiled for the target platform. But SwiftLint only builds on macOS (and Linux).

> I tested it by setting the main branch in SPM, but the result is the same.

Xcode and SPM behave a bit surprising with respect to binary dependencies. All source dependencies are still downloaded and checked out even though they won't be used in later steps. That's why you see all the packages listed in Xcode. Yet, the build should be fast (at least on `main`), because the binary SwiftLint framework is consumed to actually build/link the plugin.

**Comment by preciouslogic** [comment] 2024-01-31 10:10
ok @SimplyDanny, so will this issue be resolve or I should switch to Pod, Because i am not liking it that i have not 1 or 2 but almost 8 other libraries which i am not intended to use it.

**Comment by SimplyDanny** [comment] 2024-01-31 19:27
> ok @SimplyDanny, so will this issue be resolve or I should switch to Pod, Because i am not liking it that i have not 1 or 2 but almost 8 other libraries which i am not intended to use it.

I don't think we can do anything on the SwiftLint side. This might rather be an issue with SPM or Xcode. If you can reproduce it with a small example, you may open a ticket on their side.

**Comment by filiplazov** [comment] 2024-04-18 16:39
Hello @SimplyDanny, how about providing a binary only repository for the plugin? I think its a pretty common use case that swiftlint is consumed by iOS / Mac developers and they don't necessarily need to import the actual framework.
In our company, the main reason we are using the plugin is for an SDK project (a swift package with many modules) and we don't have build phases to invoke swiftlint. Of course we can wrap the SDK in an app and run the lint from there but its very inneficient as compared to running an individual swift module.
Do you think this is a worthy use case?

**Comment by filiplazov** [comment] 2024-04-18 16:52
What I asked above is for the purposes of avoiding "spilling out" internal Swiftlint dependencies so they are never resolved by the consumer.

**Comment by mildm8nnered** [comment] 2024-04-18 17:09
> Xcode and SPM behave a bit surprising with respect to binary dependencies. All source dependencies are still downloaded and checked out even though they won't be used in later steps. That's why you see all the packages listed in Xcode. Yet, the build should be fast (at least on `main`), because the binary SwiftLint framework is consumed to actually build/link the plugin.

I've been bitten by this before - thinking that this unnecessarily downloaded source was the source for what was executing, when it was not, and I find this SPM behaviour generally quite annoying.

I did try playing around a while ago with making a binary only package, but I don't think I got it to the point where it was working. Because of the limitations of SPM I think it might require a dedicated repo, which is also a pain.  I think it would be less confusing for the user though.

**Comment by doroshenko** [comment] 2024-06-04 13:25
I would like to second the request by @filiplazov to create a separate repo for build plugin distribution. 

After integration SwiftLint as a build plugin in our projects, we have noticed that SPM is extremely slow when doing the initial package fetch operation. This is because it is downloading an entire git repository with all commit history, branches and tags, which is case of SwiftLint is more than 1.5 GB in size just for the main repository. 

There is a long-standing issue about this on SPM Github page, but it doesn't look like it's going to be resolved any time soon: https://github.com/apple/swift-package-manager/issues/6062

As could be seen in the issue description, Lottie had the similar problem, and they were able to work around the SPM limitations it by switching to a separate repo for binary releases.

**Comment by SimplyDanny** [comment] 2024-06-18 14:01
For your interest: I'm currently working on a separate repository for the plugins that stays in sync with the main SwiftLint repository without any manual maintenance effort. I think the benefit of it will be significant compared to the hassle that's caused by the aggregation in one repository and the way SPM treats it.

**Comment by SimplyDanny** [comment] 2024-06-20 21:28
[SwiftLintPlugins](https://github.com/SimplyDanny/SwiftLintPlugins) should be ready to use now. Let me know if this matches what you were asking for. Also give a shout if something doesn't work properly.

**Comment by DD-P** [comment] 2024-06-21 01:05
This looks perfect. Thank you @SimplyDanny..

**Comment by doroshenko** [comment] 2024-06-21 08:12
@SimplyDanny I switched my projects to your repo, and everything works perfectly! Thanks a lot!

**Closed** 2024-06-25 17:07 UTC
Labels: help, integration
