### ISSUE TITLE
Support for '*' when search for files excluded?

### ISSUE THREAD

**Issue by sunkehappy** [realm/SwiftLint#1220] opened 2017-01-20 05:26 UTC
I want to ignore some files that start with _(because I'm using [mogenerator](https://github.com/rentzsch/mogenerator)). But it seems that it does nor work:

    excluded: # paths to ignore during linting. Takes precedence over `included`.
      - Carthage
      - Pods
      - oTMS_Mobile/Model/CoreDataModel/_*.swift

Is this an unsupported feature or something wrong I write above?

**Comment by aamctustwo** [comment] 2017-01-20 14:11
Is this a duplicate of #560 `Exclude files using regular expression.`?

**Comment by marcelofabri** [comment] 2017-01-20 16:24
I don't think this is exactly a duplicate because this seems to use [glob patterns](https://en.wikipedia.org/wiki/Glob_(programming)) and not regular expressions.

**Comment by jpsim** [comment] 2017-01-21 00:18
> I don't think this is exactly a duplicate because this seems to use glob patterns and not regular expressions.

Although I think we'd probably just want to stick with one and not the other. Generally the approach is to use globbing syntax when it comes to specifying files, as far as I know.

**Comment by marcelofabri** [comment] 2017-01-21 01:07
+1 for globbing and just one of them

**Comment by fcy** [comment] 2017-03-07 01:40
+1 I'd love to have a way to exclude all generated files, we put them under Generated folders. Something like this:

```
excluded:
  - **/Generated
```

Excludes files in any folder called Generated.

**Comment by jpsim** [comment] 2017-03-10 20:59
I'm all for this. Anyone know of any good file globbing libraries written in Swift that are compatible with CocoaPods, Swift Package Manager and Carthage?

**Comment by tschob** [comment] 2017-11-18 13:54
Is there any progress on #1712 or this issue?

We also have the case that we want to exclude files which are located in special folders or contain a certain string. Some of our projects are forced to use a unclean folder setup as we can't configure SwiftLint to ignore the files we need to.

#### Our background:
* Agency with a lot of projects
* One **shared** swiftlint.yml which gets copied into the project with each build (source is a submodule)

### Example with the folder `Generated`

#### Desired project setup:
```
/Root
  /App
      /Generated
  /Extensions
    /Watch
      /Generated
    /Share
      /Generated
```

#### Currently forced project setup:
```
/Root
  /App
  /Extensions
  /Generated
    /App
    /Watch
    /Share
```

**Comment by tschob** [comment] 2017-11-18 14:16
Based on the README it's possible to use Regex for `included` and `excluded` in custom rules:

```yaml
custom_rules:
  pirates_beat_ninjas: # rule identifier
    included: ".*\\.swift" # regex that defines paths to include during linting. optional.
    ...
```

@marcelofabri If Regex seems to be the way to go there, why not add it to `exclude` and `include` everythere?

If there doesn't seem to be a widely used file globbing library in Swift yet, Regex might be the way to for now.

**Comment by keith** [comment] 2018-07-24 05:16
I've implemented a possible solution for this here: https://github.com/realm/SwiftLint/pull/2316

**Comment by keith** [comment] 2018-08-02 02:16
This has been merged in https://github.com/realm/SwiftLint/pull/2316 and is part of 0.27.0. I think we can close this issue

**Closed** 2018-11-27 23:09 UTC
Labels: enhancement

**Comment by adeds** [comment] 2024-01-30 10:49
why i cannot user `**/.build/*` ?

```
warning: Cannot parse YAML file: 22:4: error: scanner: while scanning an alias in line 22, column 3
did not find expected alphabetic or numeric character:
- **/.build/*
   ^ – Falling back to default configuration
```

my rules:
```
# documentation: https://realm.github.io/SwiftLint/index.html

disabled_rules:
- trailing_whitespace
- colon
- identifier_name
- function_parameter_count
- trailing_comma
- type_name

opt_in_rules:
- empty_count
- empty_string

excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
- Frameworks
- vendor/bundle/ruby
- **/.build/*

line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

function_body_length:
    warning: 300
    error: 500

function_parameter_count:
    warning: 6
    error: 8

type_body_length:
    warning: 500
    error: 600

file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
empty_count:
    only_after_dot: true
type_name:
  max_length:
    warning: 50

reporter: "xcode"

**Comment by SimplyDanny** [comment] 2024-01-30 11:00
> why i cannot user `**/.build/*` ?

Try to surround it with quotes.

**Comment by adeds** [comment] 2024-02-06 03:58
> > why i cannot user `**/.build/*` ?
> 
> Try to surround it with quotes.

ohh i see, thanks @SimplyDanny
