### ISSUE TITLE
Colon Violation Rule doesnt apply to function arguments

### ISSUE THREAD

**Issue by Konrad77** [realm/SwiftLint#1858] opened 2017-09-28 08:17 UTC
See attached screenshot.

<img width="1010" alt="skarmavbild 2017-09-28 kl 10 14 30" src="https://user-images.githubusercontent.com/4384932/30956039-15b5e50e-a436-11e7-81ab-25a523b0d477.png">

**Comment by marcelofabri** [comment] 2017-09-28 14:14
Duplicate of https://github.com/realm/SwiftLint/issues/1074.

**Closed by marcelofabri** 2017-09-28 14:14 UTC
Labels: duplicate
