### ISSUE TITLE
empty_count still throwing false positives

### ISSUE THREAD

**Issue by gwsounddsg** [realm/SwiftLint#1657] opened 2017-07-04 14:48 UTC
issue #1622 closed this exact issue and was updated in v0.20 but false positives are still happening. Here's an example:

```swift
mutating func set(outputCount count: Int) throws {
        try check(count)
        if count == 0 { // empty_count error
                throw AveModelErr.MixerStack_badOutput(count)
        }
}
```

**Comment by marcelofabri** [comment] 2017-07-04 15:21
This is not the same issue as #1622, it's a duplicate of #827.

**Closed by marcelofabri** 2017-07-04 15:21 UTC
Labels: duplicate

**Comment by gwsounddsg** [comment] 2017-07-05 01:35
@marcelofabri could you elaborate on how this is not the same as #1622? In the example code I showed swiftlint is throwing an `empty_count` error.

**Comment by marcelofabri** [comment] 2017-07-05 08:20
#1622 is about words ending with `count`, such as `discount`. Please take a look at #827 for more discussion about your case.
