### ISSUE TITLE
crash: illegal hardware instruction swiftlint

### ISSUE THREAD

**Issue by caoer** [realm/SwiftLint#2424] opened 2018-09-28 07:08 UTC
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)?
* Installation method used (Homebrew, CocoaPods, building from source, etc)?
* Paste your configuration file:

```yml
# insert yaml contents here
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  If so, paste their relative paths and respective contents.
* Which Xcode version are you using (check `xcode-select -p`)?
* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.

```swift
// This triggers a crash:
        var crash: String {
            switch xx {
            case yy:
                return "名 \(username) 登"
            }
        }
```

**Comment by marcelofabri** [comment] 2018-10-29 22:52
Duplicate of #2276

**Closed by marcelofabri** 2018-10-29 22:52 UTC
Labels: O:User
