### ISSUE TITLE
missing_docs does not work 0.16.1

### ISSUE THREAD

**Issue by Blackjacx** [realm/SwiftLint#1383] opened 2017-03-22 22:36 UTC
Hey, 

I found that in some cases the missing_docs rule does not work as expected! The warning remains even if the documentation is provided. An example is the following:

```
/// WORKS
public struct MyStruct {
    /// DOES NOT WORK!!!
    public let constant: String

    /// WORKS
    public func test() {}
}
```

Any suggestions why that happens?

**Comment by marcelofabri** [comment] 2017-03-23 10:44
Duplicate of #728.

**Closed by marcelofabri** 2017-03-23 10:44 UTC
