### ISSUE TITLE
Homebrew formula is not up-to-date for 0.16.0 release

### ISSUE THREAD

**Issue by ceyhuno** [realm/SwiftLint#1197] opened 2017-01-16 07:55 UTC

**Comment by aamctustwo** [comment] 2017-01-16 07:58
This is a duplicate of #1173 `Homebrew hasn't been updated for v0.16.0`.

SwiftLint is still waiting on the Homebrew team to merge the PR https://github.com/Homebrew/homebrew-core/pull/8719

**Closed** 2017-01-16 12:19 UTC
