### ISSUE TITLE
empty_count rule has false positives for non-Collection comparisons

### ISSUE THREAD

**Issue by danielbyon** [realm/SwiftLint#1601] opened 2017-06-02 21:03 UTC
I'm seeing the empty_count rule triggering an error when doing a count comparison that isn't on a Collection, as shown in the screenshot below:

![screen shot 2017-06-02 at 1 46 56 pm](https://cloud.githubusercontent.com/assets/327737/26744292/2bb208ea-479a-11e7-93da-b2c1f23d07c6.png)

I think this can be solved by making the following change to Source/SwiftLintFramework/Rules/EmptyCountRule.swift line 34:

From:
`let pattern = "count\\s*(==|!=|<|<=|>|>=)\\s*0"`

To:
`let pattern = ".count\\s*(==|!=|<|<=|>|>=)\\s*0"`

This will ensure that we're checking for uses of the `count` member var, instead of checking every identifier named "count".

Running Swiftlint 0.15.0

**Comment by jpsim** [comment] 2017-06-02 21:19
Duplicate of #827

**Closed by jpsim** 2017-06-02 21:19 UTC
