### ISSUE TITLE
Wrong indent for unwrapped optional in multiline arguments

### ISSUE THREAD

**Issue by UksusoFF** [realm/SwiftLint#3163] opened 2020-04-01 09:52 UTC
### New Issue Checklist

- [v] Updated SwiftLint to the latest version
- [v] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Try `swiftlint autocorrect --format` on this code:
```swift
import Foundation

func hello(arg1: String) -> String {
    return arg1
}

func getRandomString(_ arg1: String, arg2: String, arg3: String, arg4: String) -> String? {
    let arr = [
        arg1,
        arg2,
        arg3,
        arg4
    ]

    return arr.shuffled().first
}

func mainApp() {
    let helloString = hello(
        arg1: getRandomString(
            getRandomString(
                "_arg1",
                arg2: "_arg2",
                arg3: "_arg3",
                arg4: "_arg4"
            )!,
            arg2: "arg2",
            arg3: "arg3",
            arg4: "arg4"
        )!
    )

    print(helloString)
}

mainApp()
```

Result: 
`)!` on same column with `arg4`.
```swift
func mainApp() {
    let helloString = hello(
        arg1: getRandomString(
            getRandomString(
                "_arg1",
                arg2: "_arg2",
                arg3: "_arg3",
                arg4: "_arg4"
                )!,
            arg2: "arg2",
            arg3: "arg3",
            arg4: "arg4"
            )!
    )
    ...
}
```

Expected result:
`)!` on same column with `getRandomString`.

If `getRandomString` will return non optional - all works as expected.

### Environment

* SwiftLint version (run `swiftlint version` to be sure)?
0.39.1
* Installation method used (Homebrew, CocoaPods, building from source, etc)?
Homebrew
* Paste your configuration file:
yml file not exist. Default configuration.
* Which Xcode version are you using (check `xcodebuild -version`)?
Xcode 11.4
Build version 11E146

**Comment by marcelofabri** [comment] 2020-08-04 11:57
This formatting comes from SourceKit directly and can be reproduced by using CTRL + I on Xcode. It looks like it's fixed on Xcode 12 though, so I'm closing this.

**Closed by marcelofabri** 2020-08-04 11:57 UTC
