### ISSUE TITLE
Rule name : empty_count

### ISSUE THREAD

**Issue by pranav21keshav** [realm/SwiftLint#2983] opened 2019-11-28 15:37 UTC
Even for int variables if they are compared with zero, this rule triggers error or warning
"Empty Count Violation: Prefer checking `isEmpty` over comparing `count` to zero. (empty_count)"

**Comment by marcelofabri** [comment] 2019-12-02 07:07
Duplicate of https://github.com/realm/SwiftLint/issues/827

**Closed by marcelofabri** 2019-12-02 07:07 UTC
