### ISSUE TITLE
Crash When Linting File

### ISSUE THREAD

**Issue by 72A12F4E** [realm/SwiftLint#1031] opened 2016-12-22 16:17 UTC
When I run SwiftLint against my project, I get the following error.

```
Showing All Messages
2016-12-22 10:06:44.439 swiftlint[58376:383778] *** -[__NSCFString substringWithRange:]: Range {2554, 18446744073709551614} out of bounds; string length 6539. This will become an exception for apps linked after 10.10 and iOS 8. Warning shown once per app execution.
```

This error only appears to happen after I build my project for a 2nd time. If I clean the entire project then build, this error does not occur.

This happens immediately when it starts linting a particular file in my project. I am unable to share the file, but I can give some metadata about the file

```
[me@mac]~ $ wc badFile.swift
     201     478    6539
```

I am using SwiftLint version 0.14.0

**Comment by marcelofabri** [comment] 2016-12-22 16:19
This seems to be a duplicate of https://github.com/realm/SwiftLint/issues/921.

Can you try disabling `trailing_comma` to see if it stops crashing?

**Comment by 72A12F4E** [comment] 2016-12-22 16:44
Disabling the `trailing_comma` rule seems to fix the crash. Thanks!

**Comment by marcelofabri** [comment] 2016-12-22 17:01
I'll close this so we can focus the discussion on #921 then. If you could try to reduce the file so a sample example, that'd be awesome.

**Closed by marcelofabri** 2016-12-22 17:01 UTC
Labels: bug
