### ISSUE TITLE
empty_count is triggered on variables/constants named count

### ISSUE THREAD

**Issue by JanMichaelPeter** [realm/SwiftLint#2897] opened 2019-10-11 12:25 UTC
if someone names a variable `count` and checks if its 0 like `count == 0` swiftlint throws an error and says “prefer .isEmpty() over checking count ==0” because it thinks that someone is using the method `.count()` on an array even though that is not the case

**Comment by marcelofabri** [comment] 2019-10-11 16:13
Duplicate of #827.

**Closed by marcelofabri** 2019-10-11 16:13 UTC
