### ISSUE TITLE
type_body_length rule counts comment lines as source code?

### ISSUE THREAD

**Issue by Sega-Zero** [realm/SwiftLint#372] opened 2016-01-15 12:07 UTC
Got `type_body_length` warning for my class and suddenly noticed that removing extra comments inside the class removes the warning. Shouldn't this rule count only the meaningful lines of code?

**Comment by scottrhoyt** [comment] 2016-01-15 15:57
Duplicate of #369

**Closed** 2016-01-15 15:58 UTC
