### ISSUE TITLE
Raw strings with string interpolation 

### ISSUE THREAD

**Issue by DeniZDobynda** [realm/SwiftLint#2970] opened 2019-11-20 08:03 UTC
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

You'll get an error if you lint such a file:
"""
print(#"Some text here with \\#("some") string interpolation"#)
"""

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
Linting Swift files at paths 
Linting 'main.swift' (1/1)
Illegal instruction: 4

$ swiftlint version
0.37.0
```

No configuration needed.

**Comment by marcelofabri** [comment] 2019-11-20 18:16
Duplicate of https://github.com/realm/SwiftLint/issues/2793

**Closed by marcelofabri** 2019-11-20 18:16 UTC
