### ISSUE TITLE
swiftlint autocorrect is replace `= nil {` with `nothing` (without opening brace)

### ISSUE THREAD

**Issue by daflecardoso** [realm/SwiftLint#3722] opened 2021-09-20 19:26 UTC
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

##### before

```swift
public var foo: String? = nil {
    didSet {
        //do something
    }
}
```

```bash
$ swiftlint autocorrect
```

##### after

```swift
public var foo: String?
    didSet {
        //do something
    }
}
```

**Comment by marcelofabri** [comment] 2021-09-21 07:02
Duplicate of #3718

**Closed by marcelofabri** 2021-09-21 07:02 UTC
