### ISSUE TITLE
type_name rule should allow lowercase enum cases in order to align with swift 3.0 guidelines

### ISSUE THREAD

**Issue by kremizask** [realm/SwiftLint#686] opened 2016-06-08 13:26 UTC
According to [swift-evolution](https://github.com/apple/swift-evolution/blob/master/proposals/0036-enum-dot.md) in swift 3.0, enumeration cases will have lowercase names. 

Currently such a case name is considered an error  by the type_name rule. In addition, `severity: warning` configuration is ignored by the rule. As a result, if using the new swift naming convention one currently has no other solution but to disable the rule.

**Comment by ikesyo** [comment] 2016-06-08 16:54
This would be a duplicate of #654 and #655.

**Comment by jpsim** [comment] 2016-06-08 19:52
as of #660, we allow lowercase names for enum cases.

**Closed by jpsim** 2016-06-08 19:52 UTC
