### ISSUE TITLE
Carthage support for swiftlint

### ISSUE THREAD

**Issue by vidhyasri2106** [realm/SwiftLint#1594] opened 2017-06-01 05:47 UTC
I already have carthage package manager in my Xcode project and hence deosn't want to go with cocoapods or homebrew. Is it possible to install swiftlint using carthage?

**Comment by marcelofabri** [comment] 2017-06-01 06:22
This is not supported by Carthage (yet). Duplicate of #1481.

**Closed by marcelofabri** 2017-06-01 06:22 UTC
