### ISSUE TITLE
excluded fails to match ./**/*.extension

### ISSUE THREAD

**Issue by RolandasRazma** [realm/SwiftLint#2967] opened 2019-11-17 23:16 UTC
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

excluded fails to match ./**/*.extension

I have this in config
```yml
excluded:
  - ./**/*.graphql.swift
```
but files still got matched and checked

### Environment

* SwiftLint 0.36.0
* CocoaPods

**Comment by csvrcek** [comment] 2019-11-21 23:21
@Pratix98 and I, first-time contributors, would like to contribute to this issue if nobody else was going to!

**Comment by csvrcek** [comment] 2019-11-26 22:12
@RolandasRazma we're having trouble understanding exactly what you are trying to match with the `./**/*.graphql.swift` string, could you clarify that?

**Comment by RolandasRazma** [comment] 2019-11-26 22:39
I was hoping to ignore all files in all subdirectories that end in .graphql.swift

**Comment by csvrcek** [comment] 2019-11-26 23:47
Could you send an example of the file structure that includes the files you are trying to ignore? Maybe an output from something like `tree`?

**Comment by RolandasRazma** [comment] 2019-11-27 12:39
```
tree .
.
├── A
│   ├── AA
│   │   ├── AAA
│   │   │   └── file.graphql.swift
│   │   ├── AAB
│   │   │   └── file.graphql.swift
│   │   └── file.graphql.swift
│   ├── AB
│   │   └── file.graphql.swift
│   └── file.graphql.swift
├── B
│   └── file.graphql.swift
└── file.graphql.swift
```

**Comment by csvrcek** [comment] 2019-12-02 14:15
Try using `/**/*.graphql.swift` instead, removing the `.` in the beginning.

**Comment by RolandasRazma** [comment] 2019-12-02 14:19
didn't help

**Comment by csvrcek** [comment] 2019-12-03 18:01
After some research, it looks like the `excluded` key simply allows you to ignore certain paths and doesn't allow for the recursive kind of functionality you are looking for. 

Is it possible for you to move all of your `.graphql.swift` files to a certain directory and exclude that directory?

**Comment by csvrcek** [comment] 2019-12-10 20:21
@RolandasRazma we suggest closing this issue and opening a feature request for recursive globs (not sure if you saw our above edits :) )

**Comment by marcelofabri** [comment] 2019-12-10 21:30
Closing this as duplicate of #2329

**Closed by marcelofabri** 2019-12-10 21:30 UTC
