### ISSUE TITLE
Enforcing Swiftlint Version

### ISSUE THREAD

**Issue by Mazyod** [realm/SwiftLint#1367] opened 2017-03-19 08:01 UTC
Hey, we've just integrated swiftlint into our arcanist pipeline, and we're super exited about the results!

Just one problematic experience was that some developers ended up installing outdated version of swiftlint, which lead to some confusion. Considering that swiftlint isn't backwards compatible across all versions, would it make sense to possibly add a lock file or a `min_version` in .swiftlint.yml?

Thanks,
Maz

**Comment by marcelofabri** [comment] 2017-03-19 16:22
Duplicate of #221. You can lock a version by installing with CocoaPods or by using `swiftlint_version` on your configuration file (https://github.com/realm/SwiftLint/pull/1134). 

This last option is only available on `master` though.

**Closed by marcelofabri** 2017-03-19 16:22 UTC

**Comment by c0diq** [comment] 2017-10-03 03:50
I have version 0.22 and but I see no warnings if I require a newer version of swiftlint for testing purposes.
I added that to my .swiftlint.yml file
```
swiftlint_version: 
  - 0.24.0
```
