### ISSUE TITLE
Exclude init functions from function_parameter_count rule?

### ISSUE THREAD

**Issue by garnett** [realm/SwiftLint#839] opened 2016-10-14 09:36 UTC
I have a lot of immutable models in the project (probably everyone has nowadays).

```
    //swiftlint:disable function_parameter_count
    init(ID: Int, stripeID: String, last4: String, vendor: String, expirationMonth: Int, expirationYear: Int) {
        self.ID = ID
        self.stripeID = stripeID
        self.last4 = last4
        self.vendor = vendor
        self.expirationMonth = expirationMonth
        self.expirationYear = expirationYear
    }
```

Almost every of them triggers `function_parameter_count`.
It also happens with a lot of services/viewModels due to heavy usage of constructor injection.

When I implemented this rule first I was thinking about it as a guideline which helps to expose "complex" behaviours and function calls, but I tend to think now that `init` should be excluded by default.
Happy to do a PR but it's a controversial change so should be discussed first.

**Comment by norio-nomura** [comment] 2016-10-14 12:01
This is a duplicate of #544.

**Closed by norio-nomura** 2016-10-14 12:01 UTC

**Comment by norio-nomura** [comment] 2016-10-14 12:10
I think PR will be welcomed! 😃
