### ISSUE TITLE
Analyse the source code only using Analyse option

### ISSUE THREAD

**Issue by vidhyasri2106** [realm/SwiftLint#1593] opened 2017-06-01 05:46 UTC
Hi,
I integrated Swiftlint for my xcode project. It is analysing the source code whenever i run it since i have given the script in Run script of xcode. Is it possible to analyse the code with swiftlint only if i use Analyse option of xcode(Product->Analyse) instead of Run?

**Comment by marcelofabri** [comment] 2017-06-01 06:23
Duplicate of #799.

**Closed by marcelofabri** 2017-06-01 06:23 UTC
