### ISSUE TITLE
Crash in NoSpaceInMethodCallRule

### ISSUE THREAD

**Issue by macdrevx** [realm/SwiftLint#2908] opened 2019-10-16 02:23 UTC
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Crash in `NoSpaceInMethodCallRule`

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 0.35.0
* Installation method used (Homebrew, CocoaPods, building from source, etc)? Homebrew
* Paste your configuration file:

https://github.com/GEOSwift/GEOSwift/blob/misc-updates/.swiftlint.yml
https://github.com/GEOSwift/GEOSwift/blob/misc-updates/GEOSwiftTests/.swiftlint.yml

* Which Xcode version are you using (check `xcode-select -p`)? Xcode 11.1

Steps to reproduce

* Clone https://github.com/GEOSwift/GEOSwift.git
* checkout branch misc-updates
* Run `$ swiftlint lint` in the repo root

**Comment by macdrevx** [comment] 2019-10-16 02:24
Crash log
[swiftlint_2019-10-15-220841_Andrews-MacBook-Pro.crash.zip](https://github.com/realm/SwiftLint/files/3732193/swiftlint_2019-10-15-220841_Andrews-MacBook-Pro.crash.zip)

**Comment by macdrevx** [comment] 2019-10-16 02:24
Similar crash happens under `$ swiftlint autocorrect`

**Comment by marcelofabri** [comment] 2019-10-16 05:56
Duplicate of #2793

**Closed by marcelofabri** 2019-10-16 05:56 UTC

**Comment by macdrevx** [comment] 2019-10-16 11:44
thanks @marcelofabri
