### ISSUE TITLE
Signing SwiftLint.pkg for macOS

### ISSUE THREAD

**Issue by mrvincenzo** [realm/SwiftLint#2287] opened 2018-07-10 13:01 UTC
Can Realm sign the SwiftLint.pkg binary for macOS? 

![screen shot 2018-07-10 at 15 56 03](https://user-images.githubusercontent.com/5012608/42511174-cdb08944-8459-11e8-82a6-c84729a1a509.png)

It is not really in issue in terms of installation and the app can be [easily installed ](https://support.apple.com/kb/ph25088?locale=en_US) but some people might find it daunting.

**Comment by marcelofabri** [comment] 2018-07-10 15:43
Closing as duplicate of #553.

**Closed by marcelofabri** 2018-07-10 15:43 UTC
Labels: O:User
