### ISSUE TITLE
Add Parameter Information to Rules.md

### ISSUE THREAD

**Issue by fabb** [realm/SwiftLint#2301] opened 2018-07-20 11:51 UTC
Some rules have configuration options that can be set via `.swiftlint.yml`. The possible configuration options can be seen in the `configuration` column in the output of `swiftlint rules`. It would be nice if the options would also be listed in [`Rules.md`](https://github.com/realm/SwiftLint/blob/master/Rules.md).

**Comment by marcelofabri** [comment] 2018-07-20 16:13
Duplicate of #1653

**Closed by marcelofabri** 2018-07-20 16:13 UTC
Labels: O:User
