### ISSUE TITLE
Insufficient substructure for getters

### ISSUE THREAD

**Issue by Uncommon** [realm/SwiftLint#1574] opened 2017-05-26 17:31 UTC
I've been having trouble with a rule I'm trying to write (#1471) where I'm not getting enough substructure data for the contents of getter/setter functions so my rule fails to trigger for those cases.

So I tried running the tests for all the rules in `RuleTests`, wrapping their examples in `var x: Int { ··· }` and found that ImplicitlyUnwrappedOptional, LargeTuple, LeadingWhitespace, and RedundantOptionalInitialization all fail to trigger inside getters.

Is this a bug in SourceKitten, or can it be fixed in SwiftLint?

**Comment by Uncommon** [comment] 2017-05-26 17:37
BTW some rules like ForWhere do work, so the substructure isn't completely missing. The main problem seems to be that let/var statements aren't represented.

**Comment by marcelofabri** [comment] 2017-05-26 18:06
Maybe this is https://github.com/realm/SwiftLint/issues/136 in disguise?

**Comment by Uncommon** [comment] 2017-05-26 18:23
That one talks about variables inside regular functions, which I haven't had a problem with. I wouldn't be surprised if it's related, though.

**Comment by marcelofabri** [comment] 2017-07-03 09:58
I'm closing this as a duplicate of #136. My suggestion is to upvote [SR-5057](https://bugs.swift.org/browse/SR-5057) and/or file a new issue there to track this specific example.

**Closed by marcelofabri** 2017-07-03 09:58 UTC
