### ISSUE TITLE
export lint results to file

### ISSUE THREAD

**Issue by ahmettaha** [realm/SwiftLint#1697] opened 2017-07-20 15:16 UTC
Hello,

I'm trying to save the lint results to a file on our CI server with the following run script
`
"${PODS_ROOT}/SwiftLint/swiftlint" > "${SRCROOT}/lint.txt"`

it doesnt seem to work. What am I missing?

**Comment by marcelofabri** [comment] 2017-07-20 16:12
I've tried to reproduce it on a project, but it works for me (I have tried running both in Xcode and with `xcodebuild`) 😅 . Some questions:

* Are you using SwiftLint with CocoaPods?
* Can you check if these environment variables are being set correctly?
* Maybe there's something in the build log that could be useful?

**Comment by ahmettaha** [comment] 2017-07-20 16:21
I'm running with Xcode. It creates the file, but it's empty. It seemed like there is no output from 

`"${PODS_ROOT}/SwiftLint/swiftlint"`

but, I can see the output in xcode

**Comment by marcelofabri** [comment] 2017-07-20 16:34
Do you have violations? SwiftLint prints violations to stdout, but all other info are printed to stderr.

**Comment by marcelofabri** [comment] 2017-07-26 12:10
Closing this for now. Feel free to reopen if there's anything we can help with 💯

**Closed by marcelofabri** 2017-07-26 12:10 UTC
Labels: question, repro-needed
