### ISSUE TITLE
Rule Request: make [vertical_whitespace_opening_braces] configurable

### ISSUE THREAD

**Issue by laxmorek** [realm/SwiftLint#2688] opened 2019-03-26 08:51 UTC
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### New rule request

I would like to have possibility to decide when `vertical_whitespace_closing_braces` detects inconformity. 

For example in my project I don't wanty empty whitespace after opening `func` `if` but I want to keep empty line on opening `class` or `extension`. 

I searched a few big github repos and I realized than I am not a only one who have different rule for vertical whitespace depending on what brace opens.

**Comment by marcelofabri** [comment] 2019-04-01 15:53
Duplicate of #2322.

**Closed by marcelofabri** 2019-04-01 15:53 UTC
