### ISSUE TITLE
Is `excluded:` setting for Pods directory overridden? Bug or Feature?

### ISSUE THREAD

**Issue by soberman** [realm/SwiftLint#2299] opened 2018-07-19 19:35 UTC
I currently have excluded `Pods` directory from linting inside of the `.swiftlint.yml`. However I am using manually providing paths to files that I want to lint and they include ones from the `Pods` directory. Whole command looks like this: `swiftlint --use-script-input-files --config .swiftlint.yml`.

Does it mean that the `excluded:` setting to ignore `Pods` folder in the config file is being overridden by the fact the I manually provide paths for the files? 
Is it a bug or an expected behaviour?

I am using SwiftLint 0.26.0.

**Comment by marcelofabri** [comment] 2018-07-19 19:47
Duplicate of #591.

**Closed by marcelofabri** 2018-07-19 19:47 UTC
Labels: O:User
