### ISSUE TITLE
Crash when linting raw strings with string interpolation

### ISSUE THREAD

**Issue by ChaosCoder** [realm/SwiftLint#2939] opened 2019-11-04 22:28 UTC
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

swiftlint crashes on strings that use the new [raw string syntax with hashtags](https://github.com/apple/swift-evolution/blob/master/proposals/0200-raw-string-escaping.md), if they use string interpolation with hashtags:
```swift
let str = #"Hello \#(someVariable)"#
```

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
Loading configuration from '.swiftlint.yml'
Linting Swift files at paths Test.swift
Linting 'Test.swift' (1/1)
[1]    28593 illegal hardware instruction  swiftlint lint Test.swift
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)?
0.36.0
* Installation method used (Homebrew, CocoaPods, building from source, etc)?
Homebrew

### Example
This minimal example triggers the crash:
```swift
let example = "World"
let str = #"Hello \#(example)"#
```

**Comment by marcelofabri** [comment] 2019-11-04 23:07
Duplicate of #2793

**Closed by marcelofabri** 2019-11-04 23:07 UTC
