### ISSUE TITLE
Bus Error

### ISSUE THREAD

**Issue by srikanth-vm** [realm/SwiftLint#2391] opened 2018-09-06 09:53 UTC
```bash
$ swiftlint autocorrect
```

### Environment

* SwiftLint version : 0.27.0
* Installed via Homebrew:

```yml
opt_in_rules:
  - closure_spacing
  - discouraged_optional_boolean
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - for_where
  - force_unwrapping
  - implicit_return
  - implicitly_unwrapped_optional
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - number_separator
  - object_literal
  - operator_usage_whitespace
```

* Not using nested configurations.
* Running on Xcode 9.4.1

After running for ~450 out of 600 odd files swiftlint abruptly terminates with bus error. 
Checked on multiple machines, happens only on 0.27.0. Didnt notice the error when ran on 0.25.0

**Comment by marcelofabri** [comment] 2018-09-06 16:11
Does it happen always when linting/correcting the same file? Can you try to provide a reproducible example?

Also, can you provide the stack trace?

**Comment by srikanth-vm** [comment] 2018-09-11 07:09
@marcelofabri It does not happen with the same file all the time, its random. 

Attempt 1:
```
Correcting ...
Correcting '**Cell.swift' (558/658)
[1]    39028 bus error  swiftlint autocorrect
```

Attempt 2:
```
Correcting ...
Correcting '**Helper.swift' (517/658)
[1]    39461 bus error  swiftlint autocorrect
```

**Comment by jpsim** [comment] 2018-11-28 04:05
Closing because we still have not received steps to reproduce or a stack trace, so there's nothing we can do.

**Closed by jpsim** 2018-11-28 04:05 UTC
Labels: O:User
