### ISSUE TITLE
Duplicate symbols warning after updating to Xcode 14.3

### ISSUE THREAD

**Issue by pm-dev** [realm/SwiftLint#4878] opened 2023-04-11 17:37 UTC
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

After updating to Xcode 14.3, when running swiftlint, I see the following warning output:

```
objc[11329]: Class _TtC11SwiftSyntax16BumpPtrAllocator is implemented in both /opt/homebrew/Cellar/swiftlint/0.51.0/bin/swiftlint (0x1053eb870) and /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/libSwiftSyntax.dylib (0x108e7ca10). One of the two will be used. Which one is undefined.
objc[11329]: Class _TtC11SwiftSyntax35IncrementalParseReusedNodeCollector is implemented in both /opt/homebrew/Cellar/swiftlint/0.51.0/bin/swiftlint (0x1053eba28) and /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/libSwiftSyntax.dylib (0x108e7cbc0). One of the two will be used. Which one is undefined.
objc[11329]: Class _TtC11SwiftSyntax26IncrementalParseTransition is implemented in both /opt/homebrew/Cellar/swiftlint/0.51.0/bin/swiftlint (0x1053ebac0) and /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/libSwiftSyntax.dylib (0x108e7cc58). One of the two will be used. Which one is undefined.
objc[11329]: Class _TtC11SwiftSyntax23SourceLocationConverter is implemented in both /opt/homebrew/Cellar/swiftlint/0.51.0/bin/swiftlint (0x1053ed740) and /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/libSwiftSyntax.dylib (0x108e7cd98). One of the two will be used. Which one is undefined.
objc[11329]: Class _TtC11SwiftSyntax11SyntaxArena is implemented in both /opt/homebrew/Cellar/swiftlint/0.51.0/bin/swiftlint (0x1053ed8e0) and /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/libSwiftSyntax.dylib (0x108e7cfb8). One of the two will be used. Which one is undefined.
objc[11329]: Class _TtC11SwiftSyntax18ParsingSyntaxArena is implemented in both /opt/homebrew/Cellar/swiftlint/0.51.0/bin/swiftlint (0x1053ed9e0) and /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/libSwiftSyntax.dylib (0x108e7d0b8). One of the two will be used. Which one is undefined.
objc[11329]: Class _TtC11SwiftSyntax16SyntaxAnyVisitor is implemented in both /opt/homebrew/Cellar/swiftlint/0.51.0/bin/swiftlint (0x1053ee138) and /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/libSwiftSyntax.dylib (0x108e7f940). One of the two will be used. Which one is undefined.
objc[11329]: Class _TtC11SwiftSyntax14SyntaxRewriter is implemented in both /opt/homebrew/Cellar/swiftlint/0.51.0/bin/swiftlint (0x1053f1af0) and /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/libSwiftSyntax.dylib (0x108e83a30). One of the two will be used. Which one is undefined.
objc[11329]: Class _TtC11SwiftSyntax13SyntaxVisitor is implemented in both /opt/homebrew/Cellar/swiftlint/0.51.0/bin/swiftlint (0x1053f2cd8) and /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/libSwiftSyntax.dylib (0x108e84c18). One of the two will be used. Which one is undefined.
```

### Environment

* SwiftLint version: 0.51.0
* Installation method used: Homebrew
* Xcode version: 14.3
* OS & Hardware: MacOS M1

**Comment by SimplyDanny** [comment] 2023-04-11 18:26
Duplicate of #4782.

**Closed** 2023-04-11 18:26 UTC
