### ISSUE TITLE
! before bool identified as forced unwrapping

### ISSUE THREAD

**Issue by brandonskane** [realm/SwiftLint#578] opened 2016-03-03 11:43 UTC
I'm on 0.9.1 and bools that have a "!" in front of them are incorrectly identified as a force unwrap. I need to change the !variable to variable == false for the error to go away.

**Comment by norio-nomura** [comment] 2016-03-03 13:38
Duplicate of #547

**Comment by jpsim** [comment] 2016-03-04 03:56
Closing as duplicate.

**Closed by jpsim** 2016-03-04 03:56 UTC
Labels: bug, duplicate
