### ISSUE TITLE
Rule Options Documentation

### ISSUE THREAD

**Issue by kdbertel** [realm/SwiftLint#2509] opened 2018-12-13 01:03 UTC
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

I have noticed that a number of options (for example, `modifier_order` and `trailing_comma`) have additional configuration that can be applied in the `.swiftlint.yml` file, but this configuration is not provided in the `Rules.md` file. Doing a `swiftlint rules trailing_comma` (for example) also does not provide any information, and with `modifier_order` I have found several different examples in past issues, and I don't know what it even should be now (and I tried reading the code for the rule, but I'm so unfamiliar with how rules are defined etc. that I can't make heads or tails of it). I imagine there are more rules like this, with additional configurations that can be applied.

Where can I find documentation on these optional configuration attributes on rules?

**Comment by marcelofabri** [comment] 2018-12-13 01:04
`swiftlint rules` give some information, but it's not great.

I'm closing this as duplicate of #1653.

**Closed by marcelofabri** 2018-12-13 01:04 UTC
