### ISSUE TITLE
cyclomatic_complexity cannot be disabled or configured

### ISSUE THREAD

**Issue by busce** [realm/SwiftLint#588] opened 2016-03-16 17:13 UTC
- Adding cyclomatic_complexity in the disabled_rules section, or
- Adding a custom warning or error values as no effect when I lint the project.

But ````swiftlint rules```` give the correct values.

version: 0.9.2

**Comment by jpsim** [comment] 2016-04-06 06:47
Can you please share steps to reproduce? I don't think this is a bug, but it's hard to tell with so little information.

**Comment by tsheaff** [comment] 2016-08-02 01:46
This is not happening for me. When I add `cyclomatic_complexity` to my `disabled_rules` I no longer receive warnings.

Here is my full `.swiftlint.yml`

```
disabled_rules:
  - variable_name
  - todo
  - line_length
  - file_length
  - cyclomatic_complexity

included:
  - app/source
  - siri
  - watch
  - widget
excluded:
  - Pods

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit)
```

**Comment by jpsim** [comment] 2016-08-02 21:32
I'll close this since we were never able to reproduce @busce's issues and never heard back.

**Closed by jpsim** 2016-08-02 21:32 UTC
Labels: question
