### ISSUE TITLE
brew installation error on 10.12

### ISSUE THREAD

**Issue by matteocrippa** [realm/SwiftLint#833] opened 2016-10-08 16:46 UTC
I noticed an issue trying to install swift lint under 10.12 via brew.

It fails raising those errors: https://gist.github.com/matteocrippa/5874fbd2b12bb2c56c4037db7caa6859

Any suggestion to try to fix this?

**Comment by norio-nomura** [comment] 2016-10-09 00:42
A duplicate of #815

**Closed by norio-nomura** 2016-10-09 00:42 UTC
