### ISSUE TITLE
Cannot add SwiftLint as package for Xcode plugin

### ISSUE THREAD

**Issue by fmoraes74** [realm/SwiftLint#4641] opened 2022-12-12 18:47 UTC
### New Issue Checklist

- [ ] Updated SwiftLint to the latest version
- [ ] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

I am trying to add SwiftLint as package dependency to run it as a build plugin. It fails resolution with invalid manifest.

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? Trying to pull latest
* Installation method used (Homebrew, CocoaPods, building from source, etc)? SPM

* Which Xcode version are you using (check `xcodebuild -version`)? 
 ```Xcode 14.1
Build version 14B47b```

**Comment by jpsim** [comment] 2022-12-12 19:03
I can look into this if you share more information, steps to reproduce, exact issue you're seeing, etc.

**Comment by fmoraes74** [comment] 2022-12-12 19:07
@jpsim This is what I see when I tried to add it:
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/7808154/207132529-3503999d-77a6-44f8-856b-6765f116c6da.png">

Not tried anything more than just add the `SwiftLint` package dependency and it failed with the above error.

**Comment by jpsim** [comment] 2022-12-12 19:11
We’re not using BrightFuture or FileKit, so those errors are coming from something else.

**Comment by fmoraes74** [comment] 2022-12-12 19:31
This only happens when I add SwiftLint package. I even tried with the commit from the latest version:

<img width="804" alt="image" src="https://user-images.githubusercontent.com/7808154/207136782-1e611e7a-bcab-4bbb-b716-2c7b0161a8c2.png">
<img width="412" alt="image" src="https://user-images.githubusercontent.com/7808154/207136811-08847b1e-22a8-4d60-b488-5bba79f4aab1.png">

When I try to add it, I see it come up with version 0.9.2:

<img width="840" alt="image" src="https://user-images.githubusercontent.com/7808154/207136941-2d6708c2-3efe-4ad1-bbec-aae218fb5f50.png">

**Comment by jpsim** [comment] 2022-12-12 19:41
I think your SwiftPM caches may be out of date. Please clear those and try again.

**Comment by fmoraes74** [comment] 2022-12-12 19:53
I cleaned up the directory and retried, same issue, it still shows version 0.9.2. I also noticed the following:
<img width="731" alt="image" src="https://user-images.githubusercontent.com/7808154/207141235-09d55268-80aa-4b48-b851-ab4b416d9b15.png">

**Comment by jpsim** [comment] 2022-12-12 19:59
Version 0.9.2 is from March 2016: https://github.com/realm/SwiftLint/releases/0.9.2

Please try again with 0.50.3.

**Comment by fmoraes74** [comment] 2022-12-12 20:08
I understand it is an old version but everytime I add the URL for https://github.com/realm/SwiftLint it always comes up with 0.9.2, so there is something about it that is defaulting to that version.

But even changing the version to 0.50.3 doesn't work:
<img width="809" alt="image" src="https://user-images.githubusercontent.com/7808154/207144383-057aff9d-0faa-4b84-8b55-285decca3a6c.png">

I don't know what else to try.

**Comment by jpsim** [comment] 2022-12-12 20:10
Please clear your SwiftPM caches.

This StackOverflow answer has some steps to do that: https://stackoverflow.com/a/68876107/373262

**Comment by designatednerd** [comment] 2022-12-13 03:52
I saw this a bunch of times at Apollo: There's a bug with 0.x versions where SPM doesn't understand that `0.50` is greater than `0.9`. You have to manually set it to 0.50.3.

**Comment by designatednerd** [comment] 2022-12-13 03:53
For what it's worth I'm also seeing this if I've set the version to 0.50.3 / up to next minor: 
<img width="868" alt="Screen Shot 2022-12-12 at 9 52 55 PM" src="https://user-images.githubusercontent.com/1976498/207222308-9b766e36-89db-4406-a514-210d420e32c4.png">

**Comment by Brudus** [comment] 2022-12-13 07:27
I have the same issue. I have cleared the package cache and told Xcode to fetch the exact version `0.50.3`. And I get the same error message:

Failed to resolve dependencies Dependencies could not be resolved because package 'swiftlint' is required using a stable-version but 'swiftlint' depends on an unstable-version package 'swift-syntax' and root depends on 'swiftlint' 0.50.3.

The same is true for version `0.50.1`.

Failed to resolve dependencies Dependencies could not be resolved because package 'swiftlint' is required using a stable-version but 'swiftlint' depends on an unstable-version package 'swift-syntax' and root depends on 'swiftlint' 0.50.1.

I also did this in a fresh project. I use Xcode build version: 14B47b

**Comment by jpsim** [comment] 2022-12-13 20:46
I'm not interested in maintaining this plugin. It's nothing but a headache for me so far. I might remove it from the next release and folks can provide their own SwiftLint plugins if they want to deal with these issues. cc @technocidal

**Comment by designatednerd** [comment] 2022-12-14 01:38
I can imagine this is getting a little maddening. I think it's probably worth supporting with the following caveats in the `README`: 

- You have to point to a commit or branch to use it due to these SPM "stability" requirements. If you don't like the stability requirements, file a bug with SPM, but there's nothing SwiftLint can do about them.
- This means developers cannot use it on libraries/frameworks which are brought in by other applications, only directly on the applications themselves, and you should use whatever you were using before if you're using it for a lib. 

I think that at least gives people using it directly on Applications the ability to use it, but keeps you from having to deal with all this nonsense.

**Comment by sroycoursera** [comment] 2022-12-21 22:18
I'm able to add it to the project by pointing to `main` or to a commit. When I do this, after adding the Run Build Tool Plug-ins phase, SwiftLint does work and reports code violations as expected. However the build fails at the linking phase with this message:

```
Entry point (_main) undefined. for architecture arm64
```

I haven't been able to make sense why adding the plugin affects the linker.

**Comment by technocidal** [comment] 2022-12-22 07:37
@sroycoursera 

That's probably related to https://github.com/realm/SwiftLint/issues/4628. We've reported this issue to Apple via a Feedback that they are actively looking into. Right now there isn't much we can do from our side.

**Comment by kokluch** [comment] 2022-12-27 19:13
It's because the Package.swift targets a specific revision for swift-syntax [here](https://github.com/realm/SwiftLint/blob/470d471e5100240d160b644ffba8ed6485c891e2/Package.swift#L33) which is forbidden by swift package. It requires to be updated and point to a tag.

**Comment by dherschberger** [comment] 2022-12-29 22:06
I agree with @kokluch on the explanation and request to continue to support the plugin.

Maybe just add a note to the README to tell people to consume using branch "main" if they want to use the plugin until the issue is resolved.

**Comment by shnmxvi** [comment] 2022-12-30 11:43
> It's because the Package.swift targets a specific revision for swift-syntax [here](https://github.com/realm/SwiftLint/blob/470d471e5100240d160b644ffba8ed6485c891e2/Package.swift#L33) which is forbidden by swift package. It requires to be updated and point to a tag. Looks like swift-syntax 0.50800.0 is in pre-release. When final tag will be released it's will work. It's what "unstable version" in the error message reports.
> 
> @jpsim Please don't remove the plugin, it's nice having done it. swift-syntax pre-release is 8hours ago you'll have a fix soon I guess.

with .package(url: "https://github.com/apple/swift-syntax", exact: "0.50800.0-SNAPSHOT-2022-12-20-a") does not work(

**Comment by technocidal** [comment] 2022-12-31 08:00
I'll take a look at the swift-syntax prerelease today. Maybe I can figure something out.

**Comment by technocidal** [comment] 2022-12-31 16:58
@shnmxvi 

That's correct, but the reason isn't `swift-syntx` but rather `exact` keyword in the dependency definition. This will always fail.

@jpsim 

It does however work perfectly fine when defining it like this:
`.package(url: "https://github.com/apple/swift-syntax", from: "0.50800.0-SNAPSHOT-2022-12-20-a")`.
This means that we could cut a new SwiftLint release using this dependency definition and people would be able to use that release instead of `main` .

Here is my PR: https://github.com/realm/SwiftLint/pull/4662

**Comment by shnmxvi** [comment] 2023-01-03 09:45
@technocidal 
hm, when i use `.package(url: "https://github.com/apple/swift-syntax", from: "0.50800.0-SNAPSHOT-2022-12-20-a").`i have error `Entry point (_main) undefined. for architecture arm64` (

**Comment by nkristek** [comment] 2023-01-03 10:21
@shnmxvi This might be related to #4628 and it seems to be a bug in Xcode.

**Comment by evfemist** [comment] 2023-01-09 17:25
Yeah, looks like. And even if modify plugin to define class with @main in it - then iOS app will not launch, think because of two entry points.
But I have found a temporary workaround by changing `.buildCommand` to `.prebuildCommand` for XcodeProjectPlugin.
You can check my commit [here](https://github.com/evfemist/SwiftLint/commit/bec2c95cda8cb43414ac710b7662b97072926e10)
Also there I write a crunch to hide warning "no rule to process file ..." that appears on Xcode 14.2.

**Comment by technocidal** [comment] 2023-01-09 20:11
@jpsim @evfemist 

That seems like a really good solution and, looking at the documentation, also probably more suitable for SwiftLint in the first place. `buildCommand` really seems to be more focussed on generating output.

**Comment by evfemist** [comment] 2023-01-10 13:00
With `.prebuildCommand` for **BuildToolPlugin** and **XcodeProjectPlugin** code looks much better.
Also I found that cache files was added to bundle, this is also fixed in my PR

**Comment by hunterleebrown-cbs** [comment] 2023-01-18 00:42
With `.prebuildCommand` how do I use/specify SwiftLintPlugin in the Xcode Build Phases? I'm not sure where/how to use it. 
Do I need to wait for a new release, or is this going to work from `master`?

**Comment by ryanjfar** [comment] 2023-01-25 07:57
Checking on the status of this. @evfemist branch and pr seems to fix the Xcode build plugin issue and it would be great if that could make it into the main branch.

**Comment by bdolewski-intellias** [comment] 2023-02-24 11:33
Any updates?

**Comment by SimplyDanny** [comment] 2023-02-24 14:56
@evfemist workaround has been merged and is available in the [latest release candidate](https://github.com/realm/SwiftLint/releases/tag/0.51.0-rc.2).

**Comment by SimplyDanny** [comment] 2023-07-30 15:40
There have meanwhile been some fixes concerning this issue. So I guess it can be closed for now. If there are other problems, please report new specific issues.

**Closed by SimplyDanny** 2023-07-30 15:40 UTC
Labels: help

**Comment by rzulkoski** [comment] 2023-08-11 00:37
I realize I'm super late to the party here, but I think a good solve to avoid all of these headaches is to vend the plugins from a separate repo using the binaries from the main repo. Take a look at their [Package.swift](https://github.com/SwiftGen/SwiftGenPlugin/blob/stable/Package.swift) in the plugin repo.
