### ISSUE TITLE
Homebrew formulae is outdated

### ISSUE THREAD

**Issue by ydesgagn** [realm/SwiftLint#5476] opened 2024-02-27 15:37 UTC
### New Issue Checklist

- [ ] Updated SwiftLint to the latest version (cannot do it via brew)
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

`brew info swiftlint` return swiftlint: stable 0.53.0 but 0.54.0 is out since a few months.

Can you guys update the brew formulae when you push a new version?

**Comment by SimplyDanny** [comment] 2024-02-27 15:56
Duplicate of #5353.

**Closed** 2024-02-27 15:57 UTC
