### ISSUE TITLE
Indentation Problem

### ISSUE THREAD

**Issue by sree127** [realm/SwiftLint#1527] opened 2017-05-18 07:31 UTC
Is there a reason why this indentation is not picked up as a warning? [**traling_whitespace** is being detected though] 

![screen shot 2017-05-18 at 12 54 07 pm](https://cloud.githubusercontent.com/assets/3157263/26190962/8cd8da72-3bc9-11e7-9123-6e0f73b7a6f6.png)

Attaching the swiftlint rules: 

[swiftlint_rule.txt](https://github.com/realm/SwiftLint/files/1010075/swiftlint_rule.txt)

**Comment by marcelofabri** [comment] 2017-05-18 08:12
Because there's no rule for it :)

**Comment by jpsim** [comment] 2017-05-18 23:08
Closing as a duplicate of an indentation rule request: #227

**Closed by jpsim** 2017-05-18 23:08 UTC
