### ISSUE TITLE
superfluous_disable_command scans to end of line, even if within block comment

### ISSUE THREAD

**Issue by theoriginalbit** [realm/SwiftLint#3570] opened 2021-03-12 01:00 UTC
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

I came across this issue when using PhoneNumberKit and needing to override a property that had deprecation. [Their suggestion](https://github.com/marmelroy/PhoneNumberKit#phonenumbertextfield) was to do the following
```swift
class MyGBTextField: PhoneNumberTextField {
    override var defaultRegion: String {
        get {
            return "GB"
        }
        set {} // exists for backward compatibility
    }
}
```

Which (correctly) surfaces an `unused_setter_value` violation. I attempted to silence this violation by doing the following

```swift
import PhoneNumberKit
import UIKit

class MobileTextField: PhoneNumberTextField {
    override var defaultRegion: String {
        get { "AU" }
        set { /* swiftlint:disable:this unused_setter_value */ } // exists for backward compatibility
    }
}
```

But that results in 6 violations.

```
MobileTextField.swift:7:1: Superfluous Disable Command Violation: 'compatibility' is not a valid SwiftLint rule. Please remove it from the disable command. (superfluous_disable_command)
MobileTextField.swift:7:1: Superfluous Disable Command Violation: '}' is not a valid SwiftLint rule. Please remove it from the disable command. (superfluous_disable_command)
MobileTextField.swift:7:1: Superfluous Disable Command Violation: '//' is not a valid SwiftLint rule. Please remove it from the disable command. (superfluous_disable_command)
MobileTextField.swift:7:1: Superfluous Disable Command Violation: 'exists' is not a valid SwiftLint rule. Please remove it from the disable command. (superfluous_disable_command)
MobileTextField.swift:7:1: Superfluous Disable Command Violation: 'backward' is not a valid SwiftLint rule. Please remove it from the disable command. (superfluous_disable_command)
MobileTextField.swift:7:1: Superfluous Disable Command Violation: 'for' is not a valid SwiftLint rule. Please remove it from the disable command. (superfluous_disable_command)
```

I know the simple solution here is to do the following instead

```swift
import PhoneNumberKit
import UIKit

class MobileTextField: PhoneNumberTextField {
    override var defaultRegion: String {
        get { "AU" }
        // swiftlint:disable:next unused_setter_value
        set {} // exists for backward compatibility
    }
}
```

But it definitely feels like we should be able to use a block comment like the initial example.

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 0.43.0
* Installation method used (Homebrew, CocoaPods, building from source, etc)? Homebrew
* Paste your configuration file: Irrelevant to issue

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? No
* Which Xcode version are you using (check `xcodebuild -version`)? Irrelevant to issue. Happens everywhere.
* Do you have a sample that shows the issue?

```bash
echo "/// This triggers a violation:
public struct MyType {
    /// This is an example of the problem faced when extending a type PhoneNumberKit
    public var value: String {
        get { \"AU\" }
        set { /* swiftlint:disable:this unused_setter_value */ }
    }
}" | swiftlint lint --no-cache --use-stdin --enable-all-rules
```

Outputs
```
<nopath>:6:1: warning: Superfluous Disable Command Violation: '}' is not a valid SwiftLint rule. Please remove it from the disable command. (superfluous_disable_command)
Done linting! Found 1 violation, 0 serious in 1 file.
```

**Comment by SimplyDanny** [comment] 2023-03-12 13:50
Closing this as a duplicate of #4798 which is actively being worked on.

**Closed** 2023-03-12 13:50 UTC
