### ISSUE TITLE
Support form Alcatraz

### ISSUE THREAD

**Issue by confile** [realm/SwiftLint#80] opened 2015-06-13 20:03 UTC
Could you please support installation with Alcatraz: 

https://github.com/supermarin/Alcatraz

**Comment by beltex** [comment] 2015-06-13 20:12
Hi @confile!

This would require SwiftLint to be an Xcode plugin, correct? If so, it currently does not offer that functionality. See https://github.com/realm/SwiftLint/issues/40

**Comment by bishalg** [comment] 2015-08-14 05:02
I dont know technically how difficult it is to make XCode Plugin out of SwiftLint,
but if its possible it would be awesome !

**Comment by keith** [comment] 2015-09-03 00:42
What's the benefit of having an Xcode plugin for this? You can already configure your project to run SwiftLint as a build phase if necessary?

**Comment by jpsim** [comment] 2015-09-03 15:07
I'm closing this as a duplicate of #40, because if we ever do build an Xcode plugin, it'll be made available to Alcatraz.

**Closed by jpsim** 2015-09-03 15:07 UTC
