### ISSUE TITLE
Add ability to `autocorrect` a specified set of rules

### ISSUE THREAD

**Issue by igorkotkovets** [realm/SwiftLint#1451] opened 2017-04-22 06:09 UTC
Hello guys, 

How about adding ability to run `swiftlint autocorrect` with specified set of rules? For example Xcode IDE automatically adds intended whitespaces if you press **Enter**. 
![screen shot 2017-04-22 at 9 01 59 am](https://cloud.githubusercontent.com/assets/1083951/25301891/6ca52e20-273a-11e7-97ee-3894314fe2e7.png)
So from my side it would be useful to resolve `trailing_whitespace` and `vertical_whitespace ` issues automatically, by adding `New Run Script` phase and execute a command `swiftlint autocorrect trailing_whitespace vertical_whitespace` 
![screen shot 2017-04-22 at 9 07 03 am](https://cloud.githubusercontent.com/assets/1083951/25301941/42fb709c-273b-11e7-8c4d-56e93034f6ab.png)

Thanks in advance!

**Comment by marcelofabri** [comment] 2017-04-22 19:22
You can change the Xcode behavior in this case

![](https://cloud.githubusercontent.com/assets/42419/11850228/e187fc42-a3e0-11e5-85fe-b9533518c851.png)

(from [this comment](https://github.com/realm/SwiftLint/issues/271#issuecomment-165206078))

I'll keep it open as an enhancement though.

**Comment by sunshinejr** [comment] 2017-05-14 22:13
I would actually love this feature. But wouldn't it be easier if we could use config values in e.g. `.swiftlint.yml`?

**Comment by hammadzz** [comment] 2017-05-21 10:22
@sunshinejr I guess we could add a .swiftlint.yml that ignore all rules except trailing_whitespace and run autocorrect. That would work pretty well.

**Comment by sunshinejr** [comment] 2017-05-21 20:09
I mean, whatever we need to do to make it work, I am all up for it :D

**Comment by jszumski** [comment] 2018-01-11 20:34
@igorkotkovets You can use `--config` when autocorrecting to pass in a `.yml` file with the specific rules you want. This doesn't exactly solve passing them via command line but it might be good enough for your use case.

**Comment by nishigandhadoiphode** [comment] 2018-02-01 09:51
ezs-MacBook-Pro:SwiftlintPods Nishigandha$ ./Pods/SwiftLint/swiftlint autocorrect
Loading configuration from '.swiftlint.yml'
Fatal error: Loading sourcekitd.framework/Versions/A/sourcekitd failed: file /Users/jsimard/Projects/SwiftLint/.build/checkouts/SourceKitten.git-6484296299232452758/Source/SourceKittenFramework/library_wrapper.swift, line 61
Illegal instruction: 4
ezs-MacBook-Pro:SwiftlintPods Nishigandha$ 
   

This is my error. I searched alot for this error but i am not getting whats wrong with my implementation. Please help.

**Comment by marcelofabri** [comment] 2018-02-01 10:20
@nishigandhadoiphode please file a new issue filling the issue template.

**Comment by Pe-te** [comment] 2018-04-26 12:26
>  guess we could add a .swiftlint.yml that ignore all rules except trailing_whitespace and run autocorrect. That would work pretty well.

@hammadzz is there an easy way to create such a file? Unfrtunatelly this doesn't work:
`disabled_rules:
  - all`

Would love the autocorrect parameter to correct only one rule, great idea!

**Comment by Pe-te** [comment] 2018-04-26 15:07
With easy I mean a lot simpler than this! ;p

`RULE=trailing_whitespace; ( echo "disabled_rules:"; swiftlint rules | grep -o -E '^\|[^|]*\| no' | cut -d" " -f1,2 | sed -e 's#|#  -#' | grep -v "${RULE}" ) > ".swiftlint-only-${RULE}.yml" && swiftlint autocorrect --config ".swiftlint-only-${RULE}.yml" && rm ".swiftlint-only-${RULE}.yml"`

**Comment by Pe-te** [comment] 2018-06-07 11:43
@yasirmturk It did what? o_O

**Comment by yasirmturk** [comment] 2018-06-07 11:58
fixed source code of all the Pod projects :P

**Comment by VivoEx** [comment] 2018-06-07 12:07
@yasirmturk , You may need to specify the paths to exclude in your .swiftlint.yml file, the paths which you do not want to lint.. say,
```javascript
excluded: # paths to ignore during linting. overridden by `included`.
  - Path/Pods
```

**Comment by Pe-te** [comment] 2018-06-07 15:02
oh okay, I read/understood Podfiles, sorry

**Comment by yasirmturk** [comment] 2018-06-08 09:19
this is what i did.. 
create another file `.swiftlint.auto.yml` and 
edit swiftlint build phase script as follows
![swiftlint-autocorrect](https://user-images.githubusercontent.com/306691/41150231-f0cee4d0-6b26-11e8-9ddb-611c73aae327.jpg)

**Comment by VidyaRameshkumarEmis** [comment] 2018-06-08 09:38
Yes, so did u mention the paths to exclude in your .swiftlint.auto.yml file ? if not, then it might have attempted to autocorrect all the files/folders in your swiftlint path.. for example if you have your pods folder in your swiftlint path then you would need to ask to exclude them.. Say for the same purpose mine would look something like below so autocorrect would not touch the excluded paths..
```javascript
excluded: # paths to ignore during linting. overridden by `included`.
  - /ThirdParty
  -/Pods

disabled_rules: # rule identifiers to exclude from running
  - force_cast
  - todo
```

**Comment by yasirmturk** [comment] 2018-06-08 09:54
yes i did and it runs perfectly.. 
`.swiftlint.auto.yml` is my own solution and the issue i mentioned was with the script that @Pe-te has written :)

**Comment by Pe-te** [comment] 2018-06-09 22:08
Hehe, it worked on my project because Pods and Classes are two seperate folders here and I have the .swiftlint.yml only inside Classes and run swiftlint there. Maybe adding Pods as a default exclude would be a good option? Have you checked what it does to files in .svn and .git folders?

And I really wouldn't call that a script ... maybe a snippet ... it was more meant as insipiration for the developers. look how hard it is to run only one rule in autocorrect mode, please add this as a feature! *puppy-eyes*

**Comment by yhkaplan** [comment] 2018-08-24 11:43
If anyone is interesting in one-off formatting for a single rule, I made a Swift script that runs a single rule from Swiftformat (not Swiftlint yet, sorry).

https://github.com/yhkaplan/swift-formatting-scripts/blob/master/format-only.swift

**Comment by Jeehut** [comment] 2020-06-11 14:00
Hey everyone, I just want to inform you that I will be tackling this feature request now as I was kindly asked in [this comment](https://github.com/corona-warn-app/cwa-app-ios/pull/104#issuecomment-638272327) on the open source Corona-Warn-App in Germany to split my SwiftLint fixes up into smaller PRs and I was looking for fixing each rule one by one.

My approach will be going the direction suggested from @hammadzz to basically add a new option to the `.swiftlint.yml` file, I will name it `limit_autocorrect_to` and make it accept a list of rule identifiers. That way running `swiftlint autocorrect` should be restricted to just run autocorrect for these rules.

I also considered introducing a more general `enabled_rules` that would take precedence over `disabled_rules` and `opt_in_rules` and just change the way SwiftLint works by default, then people could just provide a separate config file for the `autocorrect` command. But this seemed to be too much diagonal to the way SwiftLint was designed from the beginning and also makes this specific use case require another file, which I think is an unnecessary hurdle.

I plan to finish this up within the next few hours, but let's see how it goes ... :)

**Comment by Jeehut** [comment] 2020-06-11 15:26
Okay, forget what I just said, while implementing the feature I noticed that the alternative that I had considered (the `enabled_rules` method) is already implemented since 2016 (one year before this discussion started) by @daniel-beard in https://github.com/realm/SwiftLint/pull/436 and released in [version 0.8.0](https://github.com/realm/SwiftLint/releases/tag/0.8.0).

So, for anyone who is interested in running autocorrect for a specified set of rules, just use the approach outlined above in [this comment](https://github.com/realm/SwiftLint/issues/1451#issuecomment-395703108) above from @yasirmturk. 

Then in your separate configuration file for the autocorrection (e.g. `.swiftlint.auto.yml`), use the `whitelist_rules` option which is documented [here](https://github.com/realm/SwiftLint#configuration) in the README as following:

> Acts as a whitelist, only the rules specified in this list will be enabled. Can not be specified alongside `disabled_rules` or `opt_in_rules`.

For example, your `.swiftlint.auto.yml` file might look something like this:

```yaml
whitelist_rules:
  - comma
  - empty_parameters
  - trailing_comma
  - vertical_whitespace

trailing_comma:
  mandatory_comma: true

vertical_whitespace:
  max_empty_lines: 2
```

And you would run `swiftlint autocorrect --config '.swiftlint.auto.yml'` instead of just `swiftlint autocorrect`.

So, with a separate config file & the `whitelist_rules` option, it is already possible to do this since version 0.8.0. Thus I think this issue can be closed. What do you think? @sunshinejr

Having this said, I have just posted https://github.com/realm/SwiftLint/pull/3236 though to implement the suggestion from @castus [here](https://github.com/realm/SwiftLint/issues/1118#issuecomment-271536394) to add the `whitelist_rules` option to the YAML example to make its existence more apparent to new users.

**Comment by jszumski** [comment] 2020-06-11 18:48
Does using `--config` prevent you from using configuration inheritance in sub-directories with their own config files?

**Comment by yasirmturk** [comment] 2020-06-13 07:37
Thanks @Jeehut but it would be great any way to have atleast a section for example
```
blacklist_autocorrect:
 - bla bla
```
so, anyone can still use the original `.swiftlint.yml` and just change the script to `swiftlint autocorrect` safely or there could be other approaches like 
```
whitelist_autocorrect:
 - inherit <<special rule to inherit all whitelist rules if desired
 - additional_rule
```
in this case even the `swiftline` script can do the autocorrect job as well

**Closed** 2020-11-15 04:24 UTC
Labels: enhancement, wontfix

**Comment by drazmadzesquadpod** [comment] 2022-07-27 16:20
This would be a really helpful fix

**Comment by NikKovIos** [comment] 2024-07-18 13:32
UP 
One file for swiftlint is better that two. Less errors.

**Comment by mildm8nnered** [comment] 2024-07-18 14:24
So if you want to run a different set of rules for autocorrection, as things stand today, you will need a separate configuration file. You may be able to eliminate some redundancy in the files with parent or child configs, but the rules that will be run are a property of the configuration file. Different rule sets will need a separate file.

Slightly separately from this use case, if you want to run autocorrections for a single rule, there is now an `--only-rule` command line argument that will override rule enablement from the config file, and run just one rule. This is handy when say a new autocorrectable rule is introduced, and you want to autocorrect it, but not necessarily to run autocorrect for every correctable rule.

This is in `main` right now.
