### ISSUE TITLE
Rule Reuest : Only explicitly refer to self when required

### ISSUE THREAD

**Issue by jkmathew** [realm/SwiftLint#1373] opened 2017-03-20 06:59 UTC
As mentioned in [github's style guide](https://github.com/github/swift-style-guide#only-explicitly-refer-to-self-when-required),
When accessing properties or methods on self, leave the reference to self implicit by default. Only include the explicit keyword when required by the language—for example, in a closure, or when parameter names conflict

**Comment by marcelofabri** [comment] 2017-03-20 07:03
Duplicate of #59.

**Closed by marcelofabri** 2017-03-20 07:03 UTC
