### ISSUE TITLE
Couldn't run by dyld error

### ISSUE THREAD

**Issue by kshuin** [realm/SwiftLint#25] opened 2015-05-21 02:55 UTC
I installed `swiftlint` via homebrew, but couldn't run `swiftlint` with this error.
Is any other steps required?

```
~ % swiftlint help                                                                                                                                               
dyld: Library not loaded: @rpath/libclang.dylib
  Referenced from: /usr/local/Cellar/swiftlint/0.1.0/Frameworks/SwiftLintFramework.framework/SwiftLintFramework
  Reason: image not found
zsh: trace trap  swiftlint help
```

FYI : My environment is below

```
OS : OS X 10.10.3
Xcode : v6.3.1 (6D1002)
Shell : zsh 5.0.7 (installed via homebrew)
Location of swiftlint : /usr/local/bin/swiftlint
```

**Comment by segiddins** [comment] 2015-05-21 03:18
So you have Xcode.app installed at `/Applications/Xcode.app`?

**Comment by kshuin** [comment] 2015-05-21 05:17
@segiddins 

I have installed `/Applications/Xcode_6_3_1.app` to install multiple versions of Xcode, and my problem is resolved by rename it to `Xcode.app` . 

Thank you!!

**Comment by jpsim** [comment] 2015-05-21 07:39
I'm glad it's working now. Closing this as a duplicate of #17.

**Closed by jpsim** 2015-05-21 07:39 UTC

**Comment by jeremy-w** [comment] 2016-02-05 03:31
I'm encountering this issue attempting to use a Homebrew-installed swiftlint with TravisCI. I'm planning to work around it by not running swiftlint when Travis is doing the build.

The output I'm seeing from my Run Script build phase:

```
info: Lint Sources is beginning
info: found swiftlint at: /usr/local/bin/swiftlint
dyld: Library not loaded: @rpath/libclang.dylib
  Referenced from: /usr/local/Cellar/swiftlint/0.6.0/Frameworks/SwiftLintFramework.framework/Versions/A/SwiftLintFramework
  Reason: image not found
/Users/travis/Library/Developer/Xcode/DerivedData/Quill-gxkutrgezzklvregjpwcqvjwjrzj/Build/Intermediates/Quill.build/Debug/Quill.build/Script-3F93FDBD1C64395200119AA4.sh: line 9:  1645 Trace/BPT trap: 5       swiftlint
info: Lint Sources is ending
```

Build script:

```bash
echo "info: Lint Sources is beginning"
if which swiftlint >/dev/null; then
    echo "info: found swiftlint at: $(which swiftlint)"
    swiftlint
else
    echo "error: swiftlint not found: please run $SRCROOT/bootstrap.sh to install dependencies"
    exit 1
fi
echo "info: Lint Sources is ending"
```

Full build output: [jeremy-w/quill-steno-osx build 3](https://travis-ci.org/jeremy-w/quill-steno-osx/builds/107152478)

**Comment by norio-nomura** [comment] 2016-02-05 03:58
Xcode 7.3 beta image on Travis-CI uses `/Application/Xcode-beta.app` instead of `/Application/Xcode.app`.
swiftlint depends on libraries in `/Application/Xcode.app`.
`ln -s /Application/Xcode-beta.app /Application/Xcode.app` is a workaround for that.
