### ISSUE TITLE
Yams version needs to be updated

### ISSUE THREAD

**Issue by DesmanLead** [realm/SwiftLint#3300] opened 2020-08-13 10:40 UTC
Outdated yams version is conflicting with other useful packages, e.g. SwiftGen.
<img width="851" alt="Screenshot 2020-08-13 at 13 14 38" src="https://user-images.githubusercontent.com/2537144/90125321-85d7b680-dd6a-11ea-85a6-92bd92f81347.png">

**Comment by DesmanLead** [comment] 2020-08-13 11:18
https://github.com/jpsim/SourceKitten/issues/665

**Comment by tjprescott** [comment] 2020-08-24 21:56
+1 to this. Our project needs the latest version of YAMS and this dependency is hindering our ability to use just Swift Package Manager due to the dependency conflict.

**Comment by jpsim** [comment] 2020-08-25 02:28
I just cut releases of Yams and SourceKitten over the last few days and I'm updating to them here:https://github.com/realm/SwiftLint/pull/3319

**Comment by tjprescott** [comment] 2020-08-25 05:13
cc/ @sacheu

**Comment by jpsim** [comment] 2020-08-26 13:57
Merged #3319

**Closed by jpsim** 2020-08-26 13:57 UTC

**Comment by tjprescott** [comment] 2020-08-26 15:31
@jpsim thanks for this. When is the next release?

**Comment by jpsim** [comment] 2020-08-26 15:35
We don't have a release schedule for SwiftLint, we cut releases when there's significant changes that users might want, there are no imminent changes almost ready to land, and when a maintainer has time to cut a release.

Sounds like you might want a release asap with this change? Before we do that, could you please confirm that updating SwiftLint to master fixes whatever issues you were seeing?

**Comment by tjprescott** [comment] 2020-08-26 16:43
We have confirmed that this fix does resolve our issue. A release when convenient for you would be great! Many thanks!
