### ISSUE TITLE
Crash linting file with Extended String Delimiters

### ISSUE THREAD

**Issue by peymano** [realm/SwiftLint#2942] opened 2019-11-06 17:38 UTC
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Crashes processing this file:

```
import Foundation

private extension String {
  func test(word: String) {
    try! NSRegularExpression(pattern: #"\b\#(word)\b"#, options: .caseInsensitive)
  }
}
```

Docs on [Extended String Delimiters](https://docs.swift.org/swift-book/LanguageGuide/StringsAndCharacters.html#ID606)

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
Linting Swift files at paths
Linting 'Example.swift' (1/1)
[1]    76832 illegal hardware instruction  swiftlint lint
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)?
```$ swiftlint version
0.36.0```

* Installation method used (Homebrew, CocoaPods, building from source, etc)?
Homebrew

* Paste your configuration file:
None

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
No

* Which Xcode version are you using (check `xcode-select -p`)?
Xcode 11.2

**Comment by marcelofabri** [comment] 2019-11-06 17:57
Duplicate of #2793

**Closed by marcelofabri** 2019-11-06 17:57 UTC
