### ISSUE TITLE
Bug in empty_count rule

### ISSUE THREAD

**Issue by phoney** [realm/SwiftLint#1241] opened 2017-01-24 18:50 UTC
The empty_count rule seems to key off a variable named 'count' that isn't related to the Container.count method. In the following code there is no reference to a Container but it still generates an Empty Count violation where it shouldn't.

    func emptyCountBug(item: Int?) {
        if let count = item, count > 0 {
            print("Prefer checking isEmpty...")
        }
        if let count1 = item, count1 > 0 {
            print("No Comment")
        }
    }

**Comment by marcelofabri** [comment] 2017-01-24 18:52
Duplicate of #827.

**Closed by marcelofabri** 2017-01-24 18:52 UTC
