### ISSUE TITLE
Valid Docs should allow for return on initializers

### ISSUE THREAD

**Issue by curlymon** [realm/SwiftLint#439] opened 2016-01-28 18:51 UTC
It is quite common for documentation to include a `return` when documenting `init`s. Currently (SwiftLint 0.7.1) marks a `return` tag for an `init` as invalid under the `valid_docs` rule. You can see this is in fact an expected parameter in a number of standard libraries such as `UIKit`'s `UIView` and `UIViewController` or `Foundation`'s `NSMutableArray` as a few examples.

My thinking is that this is currently just a simple case of `init` and `init?` not being recognized as a special case that has an always implied `return`.

Any thoughts?

**Comment by jpsim** [comment] 2016-01-28 19:11
Agreed, we should definitely adapt the rule for this.

**Comment by jpsim** [comment] 2016-05-11 08:53
Closing as duplicate of #557

**Closed by jpsim** 2016-05-11 08:53 UTC
Labels: enhancement
