### ISSUE TITLE
False positive valid_docs rule for static function

### ISSUE THREAD

**Issue by freak4pc** [realm/SwiftLint#729] opened 2016-07-24 18:45 UTC
It seems the fact there's no return value isn't reognized with this specific value type. 

![image](https://cloud.githubusercontent.com/assets/605076/17085668/b4f0c4fc-51e6-11e6-95e6-0964bd806f80.png)

Adding a `/// returns: Nothing` fixes it temporarily

**Comment by freak4pc** [comment] 2016-07-24 18:47
It seems in general there is something specific I'm missing about documenting closures... Couldn't find it in the documentation.

**Comment by jpsim** [comment] 2016-07-25 17:12
Looks like a duplicate of #580.

**Closed by jpsim** 2016-07-25 17:12 UTC

**Comment by freak4pc** [comment] 2016-07-25 17:34
Oh wow sorry about that ! Totally didn't notice :)

-- 
Shai Mishali
