### ISSUE TITLE
Add rules around newlines

### ISSUE THREAD

**Issue by Noobish1** [realm/SwiftLint#548] opened 2016-02-18 19:37 UTC
So I hate redundant newlines in our codebase. We've hired some junior developers recently and they have a habit of adding redundant newlines everywhere and we'd love to see warnings/errors when they do this.

a few places they do it:
- In between functions (we normally have empty line between them)
- in function bodies (we normally have one empty line between chunks of related code)
- at the bottom of classes/structs (we normally have no empty lines at the bottom of classes/structs)

Would it be possible to add rules for the above cases?

**Comment by brentleyjones** [comment] 2016-02-24 18:24
In our style guide we have a section that basically reads as:

- Spacing:
    - Leave a single blank line at the start of a type declaration or extension.
    - Leave a single blank line before and after `// MARK:` or other grouping related comments.
    - Otherwise don't leave whitespace at the beginning or end of a scope.
- Make liberal use of single blank lines to divide code into logical chunks. Some pre-defined logical chunks are:
    - Functions
    - Commented items

This is similar to @Noobish1's rules. I would love to be able to enforce these via SwiftLint.

**Comment by jpsim** [comment] 2016-02-24 18:35
This all sounds great to me. I don't think anyone has claimed this ticket as something they were building yet, so anyone should feel free to get started on this!

**Comment by brentleyjones** [comment] 2016-02-24 19:29
Btw, #305 is a duplicate of this now.

**Comment by masters3d** [comment] 2016-08-09 04:45
Do we need a new rule or could TrailingWhitespaceRule be modified to also complain about pure newlines?

**Comment by masters3d** [comment] 2016-08-09 17:55
Never mind, this would be confusing with the ``TrailingNewlineRule``.

**Closed** 2016-08-22 20:55 UTC
Labels: help wanted, rule-request
