### ISSUE TITLE
Warnings running with Xcode 14.3

### ISSUE THREAD

**Issue by NachoSoto** [realm/SwiftLint#4881] opened 2023-04-12 14:53 UTC
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Not sure if I messed up my installation, but ever since I updated to SwiftLint 0.51.0 and Xcode 14.3, I see these warnings every time I run it:
```
objc[76936]: Class _TtC11SwiftSyntax16BumpPtrAllocator is implemented in both /opt/homebrew/Cellar/swiftlint/0.51.0/bin/swiftlint (0x1039ef870) and /Applications/Xcode-14.3.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/libSwiftSyntax.dylib (0x107480a10). One of the two will be used. Which one is undefined.
objc[76936]: Class _TtC11SwiftSyntax35IncrementalParseReusedNodeCollector is implemented in both /opt/homebrew/Cellar/swiftlint/0.51.0/bin/swiftlint (0x1039efa28) and /Applications/Xcode-14.3.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/libSwiftSyntax.dylib (0x107480bc0). One of the two will be used. Which one is undefined.
objc[76936]: Class _TtC11SwiftSyntax26IncrementalParseTransition is implemented in both /opt/homebrew/Cellar/swiftlint/0.51.0/bin/swiftlint (0x1039efac0) and /Applications/Xcode-14.3.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/libSwiftSyntax.dylib (0x107480c58). One of the two will be used. Which one is undefined.
objc[76936]: Class _TtC11SwiftSyntax23SourceLocationConverter is implemented in both /opt/homebrew/Cellar/swiftlint/0.51.0/bin/swiftlint (0x1039f1740) and /Applications/Xcode-14.3.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/libSwiftSyntax.dylib (0x107480d98). One of the two will be used. Which one is undefined.
objc[76936]: Class _TtC11SwiftSyntax11SyntaxArena is implemented in both /opt/homebrew/Cellar/swiftlint/0.51.0/bin/swiftlint (0x1039f18e0) and /Applications/Xcode-14.3.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/libSwiftSyntax.dylib (0x107480fb8). One of the two will be used. Which one is undefined.
objc[76936]: Class _TtC11SwiftSyntax18ParsingSyntaxArena is implemented in both /opt/homebrew/Cellar/swiftlint/0.51.0/bin/swiftlint (0x1039f19e0) and /Applications/Xcode-14.3.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/libSwiftSyntax.dylib (0x1074810b8). One of the two will be used. Which one is undefined.
objc[76936]: Class _TtC11SwiftSyntax16SyntaxAnyVisitor is implemented in both /opt/homebrew/Cellar/swiftlint/0.51.0/bin/swiftlint (0x1039f2138) and /Applications/Xcode-14.3.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/libSwiftSyntax.dylib (0x107483940). One of the two will be used. Which one is undefined.
objc[76936]: Class _TtC11SwiftSyntax14SyntaxRewriter is implemented in both /opt/homebrew/Cellar/swiftlint/0.51.0/bin/swiftlint (0x1039f5af0) and /Applications/Xcode-14.3.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/libSwiftSyntax.dylib (0x107487a30). One of the two will be used. Which one is undefined.
objc[76936]: Class _TtC11SwiftSyntax13SyntaxVisitor is implemented in both /opt/homebrew/Cellar/swiftlint/0.51.0/bin/swiftlint (0x1039f6cd8) and /Applications/Xcode-14.3.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/libSwiftSyntax.dylib (0x107488c18). One of the two will be used. Which one is undefined.
```

### Environment

* SwiftLint version: 0.51.0
* Installation method used: Homebrew
* Which Xcode version are you using:  14.3 (14E222b)

**Comment by SimplyDanny** [comment] 2023-04-12 18:14
Duplicate of #4782.

**Closed** 2023-04-12 18:15 UTC
Labels: bug, duplicate
