### ISSUE TITLE
Issue with shorthand violations (CGRect offsetBy)

### ISSUE THREAD

**Issue by Konrad77** [realm/SwiftLint#1204] opened 2017-01-17 07:21 UTC
I've got an error with the following code. 
<img width="1110" alt="skarmavbild 2017-01-17 kl 08 13 58" src="https://cloud.githubusercontent.com/assets/4384932/22011127/a2470a50-dc8d-11e6-844c-87717e27a309.png">

However, the following code seems fine for the "_Shorthand_":
controller.view.frame = controller.view.frame.offsetBy(dx: controller.view.frame.width, dy: 0.0)

**Comment by marcelofabri** [comment] 2017-01-17 15:15
Duplicate of #1156 and fixed on #1157

**Closed by marcelofabri** 2017-01-17 15:15 UTC
