### ISSUE TITLE
WaLinting error

### ISSUE THREAD

**Issue by amichail** [realm/SwiftLint#503] opened 2016-02-07 01:16 UTC
What does this error mean?

WaLinting '<filename>' (4/17)

The filename mentioned is different from the file in which this error is shown.

**Comment by amichail** [comment] 2016-02-07 01:23
The error went away after disabling the  nesting rule.

**Comment by jpsim** [comment] 2016-02-07 01:28
The issue here seems to be that SwiftLint logs both to stderr and stdout simultaneously, and that despite using a serial queue to do all prints (see https://github.com/realm/SwiftLint/blob/0.8.0/Source/SwiftLintFramework/Extensions/QueuedPrint.swift#L11-L20), `print` and `fputs` aren't fully synchronous calls.

The solution here might be to use `fputs` for both `queuedPrint(_:)` and `queuedPrintError(_:)`, and call `fflush()` after each print. Or maybe [`setvbuf()`](http://www.freebsd.org/cgi/man.cgi?query=setvbuf) is the answer...

**Comment by jpsim** [comment] 2016-02-07 01:29
We're already tracking this as #432, so I'll close this one as a duplicate.

**Closed by jpsim** 2016-02-07 01:29 UTC

**Comment by jpsim** [comment] 2016-02-07 01:31
We'll soon have a `--quiet` flag that will avoid logging to stderr (#497) which would also avoid this issue, but obviously not fixing the root cause, which is something we should do.
