### ISSUE TITLE
valid_docs incorrectly expects return documentation when method definition includes inline closure argument

### ISSUE THREAD

**Issue by chadmoone** [realm/SwiftLint#656] opened 2016-05-09 16:10 UTC
The following will incorrectly trigger an `invalid_docs` warning:

```swift
 /**
Asynchronous method which does something.

- parameter foo: The foo with which to do the thing.
- parameter completion: A closure called upon completion.
*/
public func doSomething(foo: String, completion: () -> ()) {
    // Implementation
}
```

Adding a `- returns:` declaration will silence the error:
```swift
 /**
Asynchronous method which does something.

- parameter foo: The foo with which to do the thing.
- parameter completion: A closure called upon completion.

- returns: blahblahblah
*/
public func doSomething(foo: String, completion: () -> ()) {
    // Implementation
}
```

This seems like a pretty common occurrence.

**Comment by sofili** [comment] 2016-06-01 22:42
same for ///

**Comment by cdzombak** [comment] 2016-06-23 19:39
does this duplicate #580?

**Comment by chadmoone** [comment] 2016-06-23 21:16
It looks like this is the same issue.  Changing the closure return type to `Void` will prevent the warning here, and adding an erroneous return documentation on the function will prevent the warning in #580.

Verified with 0.11.1

**Comment by jpsim** [comment] 2016-07-08 14:34
going to close this as a duplicate of #580

**Closed by jpsim** 2016-07-08 14:34 UTC
Labels: bug
