### ISSUE TITLE
Add rule for proper indentation with preconfigured number of spaces

### ISSUE THREAD

**Issue by Johennes** [realm/SwiftLint#227] opened 2015-11-22 08:25 UTC
It would be great to check for a consistent indentation using e.g. 2 or 4 space for each level of nesting. Here are some violating examples:

``` swift
class Foo {
let bar: String
}
```

``` swift
class Foo {
    func bar() {
      return "foo"
    }
}
```

In addition, it'll also be nice to check for a consistent indentation of multi-line array/dictionary or string constructs. Violating examples:

``` swift
let a = ["foo",
"foo",
"foo"]
```

``` swift
let a = "foo"
+ "bar"
+ "foobar"
```

**Comment by ecnepsnai** [comment] 2016-03-18 23:06
Any update on this @jpsim ?  Would really value this rule.

**Comment by jpsim** [comment] 2016-03-18 23:09
It's up for grabs, no one has started work on this as far as I know.

**Comment by arsonik** [comment] 2016-05-19 07:31
+1

**Comment by qasim** [comment] 2016-07-14 05:09
Working on this over at https://github.com/realm/SwiftLint/compare/master...qasim:qasim/add-indentation. ☺️

**Comment by salutis** [comment] 2016-10-25 12:27
@qasim Any updates on this one?

**Comment by ldiqual** [comment] 2016-11-28 07:14
@Johennes @salutis @ecnepsnai I've created a PR addressing the first part of this issue. Please feel free to 👍 if you'd like to express interest! https://github.com/realm/SwiftLint/pull/873

**Comment by fredpi** [comment] 2020-01-06 09:38
The new `indentation_width` opt-in rule is now available (see https://github.com/realm/SwiftLint/pull/2765), so maybe we can close this issue? Or should we wait until there's also a more advanced / flexible indentation rule?

**Comment by jpsim** [comment] 2020-01-06 16:51
Let's close this. Anyone should feel empowered to file new, more specific issues about further enhancements. Thanks @fredpi!

**Closed by jpsim** 2020-01-06 16:51 UTC
Labels: rule-request

**Comment by keith** [comment] 2020-01-08 19:00
FYI it looks like this rule is incompatible with this style:

```swift
        XCTAssertEqual(foo,
                       "blah")
```

which we use when the first line would overflow our column length limit

**Comment by fredpi** [comment] 2020-01-08 19:02
@keith That's by design, as the rule suggests the following style in case of overflow:

```swift
XCTAssertEqual(
   foo,
   "blah"
)
```

**Comment by jpsim** [comment] 2020-01-08 21:02
It' be awesome to add a configuration option to support the first style too.

**Comment by patrickbdev** [comment] 2020-08-09 20:52
@fredpi @jpsim was support added for the first style?
It'd be useful for instances like:
```
[textField,
 callButton].forEach(addSubview)
```

**Comment by fredpi** [comment] 2020-08-10 06:41
@patrickbdev Unfortunately, that's not yet available and currently, I don't have the time to implement it 🙁 Feel free though to open a new issue specifically explaining the desired changes!

**Comment by fredpi** [comment] 2020-08-26 07:55
@hisavali This is expected behavior, as autocorrection is not yet available for the `indentation_width` rule. Feel free to open a dedicated issue to track progress on such a feature.
