### ISSUE TITLE
wrong warning for isEmpty rule

### ISSUE THREAD

**Issue by amrangry** [realm/SwiftLint#2934] opened 2019-10-31 09:55 UTC
When i use the below code:

```
guard  count  > 0 else  {
   return
}
```

BTW count is Int

I got the following issue 

> Empty Count Violation: Prefer checking `isEmpty` over comparing `count` to zero. (empty_count)

**Comment by marcelofabri** [comment] 2019-10-31 15:45
Duplicate of #827

**Closed by marcelofabri** 2019-10-31 15:45 UTC
