### ISSUE TITLE
rule to check when comparing to the same object

### ISSUE THREAD

**Issue by masters3d** [realm/SwiftLint#1503] opened 2017-05-08 23:06 UTC
```swift
if someObj == someObj {} // always true
if objA != objA {} // always false
```

Same goes goes for < and > which are always false when comparing to self.

**Comment by marcelofabri** [comment] 2017-05-09 05:42
Duplicate of #1371

**Closed by marcelofabri** 2017-05-09 05:42 UTC

**Comment by masters3d** [comment] 2018-02-23 23:41
haha, I filed this rule multiple times! I should just implement it so it goes out of my head!
