### ISSUE TITLE
What is the reason for the optional binding rule?

### ISSUE THREAD

**Issue by BilalReffas** [realm/SwiftLint#1468] opened 2017-04-26 19:53 UTC
The latest `swiftlint` version has a new `unused_optional_binding` rule. What is the reason for it? I just want to understand that  🤔

**Comment by SDGGiesbrecht** [comment] 2017-04-26 20:58
`unused_optional_binding` helps you catch things like...

```swift
if let _ = Int(exactly: 1.1) {
    print("?!?")
}
```

...and replace them with...

```swift
if Int(exactly: 1.1) != nil {
    print("?!?")
}
```

The reasoning that the second example is clearer to read as its purpose is more self‐evident.

***

P.S. I do not know which is actually more efficient after compiler optimizations. Does anyone else know?

**Comment by tariq235** [comment] 2017-04-28 07:45
First function is more readable. I'd to disable unused_optional_binding.

**Comment by BilalReffas** [comment] 2017-04-28 07:46
Same here ...

**Comment by marcelofabri** [comment] 2017-04-28 07:51
Duplicate of #1446 and #1432

**Closed by marcelofabri** 2017-04-28 07:51 UTC

**Comment by SDGGiesbrecht** [comment] 2017-04-28 19:51
@tariq235, @BilalReffas 

> First function is more readable.

Some days I agree with you. Other days the rule seems to make a lot of sense. I haven’t really decided yet what I think of this particular rule myself.
