### ISSUE TITLE
Improve first-time user experience

### ISSUE THREAD

**Issue by salutis** [realm/SwiftLint#3380] opened 2020-10-12 12:02 UTC
Someone’s first-time experience might look like this:

```
% swiftlint --help 
Unrecognized arguments: —help

% swiftlint -h 
Unrecognized arguments: -h

% man swiftlint
No manual entry for swiftlint
```

This is suboptimal.

**Comment by jpsim** [comment] 2020-11-07 23:39
Totally agreed. This is a duplicate of https://github.com/realm/SwiftLint/issues/531

**Closed by jpsim** 2020-11-07 23:39 UTC
