### ISSUE TITLE
Command line parser doesn't accept spaces in path

### ISSUE THREAD

**Issue by eholley** [realm/SwiftLint#3471] opened 2020-12-17 21:41 UTC
### New Issue Checklist

- [x] Updated SwiftLint to the latest version\
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Perhaps due to the new command line parser recently introduced, spaces in the "--config" option's value are not accepted. 

##### Complete output when running SwiftLint, including the stack trace and command used

Example structure:
- "test1"
- - baseline.yml
- "test 2"
- - baseline.yml

```bash
swiftlint --config /Users/erik/Desktop/test1/baseline.yml --path /Users/erik/Desktop/test1
Linting Swift files at paths /Users/erik/Desktop/test1
No lintable files found at paths: '/Users/erik/Desktop/test1'

swiftlint --config "/Users/erik/Desktop/test 2/baseline.yml" --path "/Users/erik/Desktop/test 2"
error: SwiftLint Configuration Error: Could not read file at path: /Users/erik/Desktop/test
Could not read configuration: file Configuration.swift, line 236
zsh: abort      swiftlint --config "/Users/erik/Desktop/test 2/baseline.yml" --path 
```
### Environment

* SwiftLint version 0.42.0
* Installation method used Homebrew
* Paste your configuration file:

```yml
# nothing
```

**Comment by matteobart** [comment] 2021-01-14 00:17
Not sure how this should be handled because it seems like spaces are sometimes used in strings to show that there are multiple files. 

From the readme: 

> A simple example including just two configuration files looks like this:
> 
> swiftlint --config ".swiftlint.yml .swiftlint_child.yml"

Link: https://github.com/realm/SwiftLint#command-line-1

In general, spaces should be avoided in naming folders and filenames. It's possible that there is no actual fix for this issue.

**Comment by justin** [comment] 2021-01-14 15:16
@matteobart - this worked for years, up until the last release. I'd consider it a regression in functionality. I found a way to work around this bug for now because it did break out builds, but it's not ideal long-term. 

I'd be happy to try and look at a fix if one of the project owners or contributors could offer some guidance on where I should start looking.

**Comment by jpsim** [comment] 2021-02-23 21:43
Could you please try this again on `master` or [0.43.0-rc.3](https://github.com/realm/SwiftLint/releases/tag/0.43.0-rc.3) now that we've migrated to use swift-argument-parser?

**Comment by tarbayev** [comment] 2021-06-16 07:32
0.43.1 Still has this issue. It's critical for us, as we have a lot of legacy code and would like to lint only modified files in our CI.
Our issue is a bit different, but most probably has same cause. The `<paths>` argument is not being parsed correctly. Escaping whitespaces has no effect, it's still splitting the strings by whitespaces.

**Comment by SimplyDanny** [comment] 2022-05-01 20:18
I cannot reproduce the issue in the most recent version 0.47.1.

**Closed by SimplyDanny** 2022-05-01 20:18 UTC
