### ISSUE TITLE
Bug Fix: Crash when parsing variable names containing unicode only characters

### ISSUE THREAD

**Issue by valdirunars** [realm/SwiftLint#1406] opened 2017-03-30 17:32 UTC
If variable name is an emoji swiftlint crashes

```line 7:  1225 Illegal instruction: 4  swiftlint```

**Comment by kimdv** [comment] 2017-03-30 18:12
It can maybe be related to #1336

**Comment by valdirunars** [comment] 2017-03-30 18:15
Not really error is happening when I do this

```swift
init { 👷 in
    👷.variable = value
}
```

**Comment by marcelofabri** [comment] 2017-04-07 22:44
Closing as a duplicate of #1006.

**Closed by marcelofabri** 2017-04-07 22:44 UTC
Labels: bug
