### ISSUE TITLE
Multiple empty lines

### ISSUE THREAD

**Issue by Najdan** [realm/SwiftLint#305] opened 2015-12-31 07:12 UTC
It should show warning if there are multiple empty lines one after another. Didn't noticed this rule and it would be good to have it.

Example:
```swift
func a() {
}





func b() {
}



var abc = "test"
```
Should be something like this:
```swift
func a() {
}

func b() {
}

var abc = "test"
```

**Comment by jpsim** [comment] 2016-02-24 22:34
Closing as a duplicate of #548.

**Closed by jpsim** 2016-02-24 22:34 UTC
Labels: rule-request
