### ISSUE TITLE
ValidDocsRule warn when non-throwing function accept throwing closure as argument.

### ISSUE THREAD

**Issue by vgorloff** [realm/SwiftLint#270] opened 2015-12-15 11:26 UTC
Here is an example code which raise swiftlint warning:
~~~swift
/// Executes throwing expression and prints error if happens.
/// - parameter closure: Expression to execute.
/// - returns: nil if error happens, otherwize returns some value.
public func trythrow<T>(@autoclosure closure: () throws -> T?) -> T? {
	do {
		return try closure()
	} catch {
		print(error)
		return nil
	}
}
~~~

I guess issue addressed to this piece of code (see file `ValidDocsRule.swift`):
~~~swift
func superfluousOrMissingThrowsDocumentation(declaration: String, comment: String) -> Bool {
    return declaration.containsString(" throws ") == !comment.containsString("- throws:")
}
~~~

Thanks! .)

**Comment by jpsim** [comment] 2015-12-15 20:55
Duplicate of #267.

**Closed by jpsim** 2015-12-15 20:55 UTC
