### ISSUE TITLE
Illegal instruction: 4

### ISSUE THREAD

**Issue by mcandre** [realm/SwiftLint#2236] opened 2018-06-08 20:20 UTC
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint
Fatal error: Loading sourcekitd.framework/Versions/A/sourcekitd failed: file /private/var/folders/h8/m8y370cn01b48nf996ccswsw0000gn/T/mint_550169050.6607/github.com_realm_SwiftLint/.build/checkouts/SourceKitten.git-6484296299232452758/Source/SourceKittenFramework/library_wrapper.swift, line 66
Illegal instruction: 4
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? `0.25.1`
* Installation method used (Homebrew, CocoaPods, building from source, etc)? `mint`
* Paste your configuration file: (none)
* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? N/A
* Which Xcode version are you using (check `xcode-select -p`)? `/Library/Developer/CommandLineTools`
* Do you have a sample that shows the issue? https://github.com/mcandre/tonixxx/blob/issue-58/examples/levitate/Source/levitate/main.swift

**Comment by norio-nomura** [comment] 2018-06-09 00:03
closing this as a duplicate of https://github.com/realm/SwiftLint/issues/1466

**Closed by norio-nomura** 2018-06-09 00:03 UTC
Labels: O:User
