### ISSUE TITLE
count rule bugged

### ISSUE THREAD

**Issue by jonasman** [realm/SwiftLint#1080] opened 2016-12-29 09:44 UTC
`if count > 0 {`
if my var is called count it will be marked as a empty_count failure.

It should check if there is a dot before the count

**Comment by marcelofabri** [comment] 2016-12-29 14:27
This is by design as the rule should be able to catch usages of `count` inside `Array` extensions for example. See https://github.com/realm/SwiftLint/issues/827#issuecomment-263009822 for more details.

As there's already another issue tracking the problem, I'll close this as a duplicate. Feel free to jump in the discussion in #827.

**Closed by marcelofabri** 2016-12-29 14:27 UTC
