### ISSUE TITLE
False positive for overridden_super_call

### ISSUE THREAD

**Issue by jdmarshall90** [realm/SwiftLint#1360] opened 2017-03-16 01:36 UTC
```swift
class MyView: UIView {
    override func updateConstraints() {
        defer { super.updateConstraints() }
        
        guard condition == true else { return }

        // add constraints ...
    }
}
```

Or

```swift
class MyVC: UIViewController {
    override func viewDidLoad() {
        defer { super.viewDidLoad() }
    }
}
```
Both trigger `overridden_super_call`.

**Comment by marcelofabri** [comment] 2017-03-16 01:38
Duplicate of #1301.

**Closed by marcelofabri** 2017-03-16 01:38 UTC
