### ISSUE TITLE
Xcode hanging when applying SwiftLint to many targets 

### ISSUE THREAD

**Issue by Mistakx** [realm/SwiftLint#4844] opened 2023-03-28 10:39 UTC
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug
I'm currently trying to add SwiftLint as a Build Tool Plug-In in Xcode.
The repo has a Package, and that package has around 70 targets. 
Adding the plugin to every target currently makes it so Xcode gets stuck while building the project.

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 0.51.0
* Installation method used (Homebrew, CocoaPods, building from source, etc)? Build Tool Plug-In
* Paste your configuration file: N/A

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? No
* Which Xcode version are you using (check `xcodebuild -version`)? 14.2.0
* Do you have a sample that shows the issue? N/A

**Comment by geertbleyen** [comment] 2023-03-30 13:38
I'm experiencing the same thing. It takes up to 50 seconds in the Prepare packages part before the build actually starts, where all this time is spent on SwiftLint.
![image](https://user-images.githubusercontent.com/71486361/228853972-2ae7068e-6129-4510-8bbd-5657a0a0e317.png)

Using Xcode 14.3 and SwiftLint 0.51.0

**Comment by geertbleyen** [comment] 2023-03-30 14:21
Additional info: previously we were using cdd891a4a29cfd3473737857385f79c972702293, which didn't have this issue.
Reason for using that version previously was that:
- we had an in-house version for the SPM buildtool plugin to run SwiftLint on our SPM packages. This in-house version also used the binaryTarget and had the same name, so we had to stick with a version of SwiftLint that didn't use the binaryTarget for the buildtool plugin.
- Getting rid of our in-house version wasn't possible until the SPM dependency issue with relying on 'unstable' versions was resolved (which happened only in 0.51.0 if I'm not mistaken).

I've now spent hours in switching all our SPM packages to use SwiftLint 0.51.0 (which by themselves works ok as seen in the screenshot above, although individual SPM packages are rather small for us).
Only at the end of my work, where the 'big' application starts now consuming those packages and integrates SwiftLint itself, did this issue show up.

**Comment by geertbleyen** [comment] 2023-03-31 08:21
For now I decided to temporarily use SwiftLint as script in the target's buildphases to mitigate this issue.
Fyi, running SwiftLint on the application folder takes ~1.7 seconds for linting 85 files (running swiftlint "application source folder) vs 30-50 seconds when using the buildtool plugin.

**Comment by sky-SergioOliveira** [comment] 2023-03-31 10:03
@geertbleyen Same here, using SwiftLint as script looks to be the solution for now. It's unfortunate, because we were looking to replace it with the plugin, as to not have the dependencies on each of the devs local machine.

**Comment by andyyhope** [comment] 2023-04-21 05:27
Also seeing massive regressions for the BuildTool plugin (~300 seconds for 1500 files) whereas the script only takes a few seconds.

**Comment by engineeric** [comment] 2023-04-25 21:59
Similar experience for an Xcode project with 1247 files.
- 0.51.0: 303.5 seconds
- 0.50.3: 4.7 seconds

**Comment by Mordil** [comment] 2023-04-27 18:25
Yeah, this is a major pain point for us as well. We're not in a great position to just easily switch to using SwiftLint as a script instead of a build plugin

Could this be prioritized for a patch fix?

**Comment by andyyhope** [comment] 2023-05-03 01:47
I've looked into this issue and traced the cause of the issue. I've put a PR to address it: https://github.com/realm/SwiftLint/pull/4955

**Comment by berlisa** [comment] 2023-05-11 09:23
We also have the problem, that our build freezes when we use the SwiftLint-Plugin in too many targets.
But I found out that this happens with any type of plugin:
I removed SwiftLint and the plugins from our project and targets.. then I built a dummy buildTool plugin (without functionality) and added the dummy plugin to our targets.. and the outcome is xcode(build) freezes.. 
Because of that, I think the problem is not the Swiftlint plugin.. it seems that Xcode(build) ha a problem with to many plugins used in targets.
In our project the build is working when we use the plugin in <= 73 targets..  more targets with the plugin (> 73) freezes the build.
It seems like a Xcode(build)/Apple bug.

**Comment by SimplyDanny** [comment] 2023-05-11 17:05
The issue on the SwiftLint side was fixed. What remains seems to be an Xcode issue. Therefore I'm going to close this ticket.

**Closed as completed** 2023-05-11 17:05 UTC
Labels: bug

**Comment by andyyhope** [comment] 2023-05-12 01:10
@SimplyDanny I think there may be *one* more optimisation we could do but I haven't got much bandwidth to investigate.

Inside the implementation of:
```
public func filterExcludedPaths(_ excludedPaths: [String], in paths: [String]...) -> [String]
```

I noticed that `paths` is an array of 1 element when using an Swift Plugin context. You could prob speed things up even more if you tweak the `result` mutation method here. 
https://github.com/realm/SwiftLint/blob/3cf9585b2e0a4a9bd8380166b496eb2e02de68d8/Source/SwiftLintCore/Extensions/Configuration%2BLintableFiles.swift#L85

Just my 2c

**Comment by AliTavakoliFFW** [comment] 2024-03-20 10:07
Is there any solution for that problem?
I face the same issue. Xcode 15.3, SwiftLint .54.0 as Plugin 
As Plugin takes 213 Seconds.
As BuidPhase(Pods) just 23 Seconds.
