### ISSUE TITLE
operator_usage_whitespace treats multiline generic specializations as operands

### ISSUE THREAD

**Issue by lazarevzubov** [realm/SwiftLint#3960] opened 2022-04-26 18:32 UTC
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

There's still an issue with generic parameters, if they're placed on different lines. This:

```swift
let something = Something<GenericParameter1,
                          GenericParameter2>()
```

Becomes this:

```swift
let something = Something < GenericParameter1,
                          GenericParameter2 > ()
```

### Environment

* SwiftLint version [0.47.1](https://github.com/realm/SwiftLint/releases/tag/0.47.1)
* Installation method used–Homebrew

* Which Xcode version are you using (check `xcodebuild -version`)? 13.3.1

**Comment by marcelofabri** [comment] 2022-04-28 06:17
Duplicate of https://github.com/realm/SwiftLint/issues/3668

**Closed by marcelofabri** 2022-04-28 06:17 UTC
Labels: bug
